### ISSUE TITLE
:four_leaf_clover: `Proposal`: Add `-d, --plugin-dir` Flag to `dtm destroy` Command

### ISSUE THREAD

**Issue by daniel-hutao** [devstream-io/devstream#1051]
## What Would You Like to Add? Why Is This Needed?

`-d, --plugin-dir string    plugins directory`

## Design

We can specify plugin directory when `Create`/`Delete`, so it's definitely clear that we need `-d, --plugin-dir` flag with `Destroy`.

## Anything else

Maybe this proposal could be implemented with #1050

**Comment by csonezp** [comment]
please assign it to me, i want to try

**Comment by daniel-hutao** [comment]
@csonezp I'm sorry for the delay response, and you get it now. Enjoy for the coding!
