### ISSUE TITLE
:bomb: `Bug`: The quick-start script is missing the version number when configuring the download

### ISSUE THREAD

**Issue by aFlyBird0** [devstream-io/devstream#1072]
### What Happened?

https://raw.githubusercontent.com/devstream-io/devstream/main/hack/quick-start/quickstart.sh

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/36830265/188829958-2ec4bcc0-e4fe-421c-96a9-2d990381dc63.png">

It should refer to the branch where the latest release is located.

## Correspondence between Branch Name and Version Number：

https://docs.devstream.io/en/latest/development/branch-and-release/

<img width="735" alt="image" src="https://user-images.githubusercontent.com/36830265/188830367-9b35edbe-7129-4349-b444-3e3446d67989.png">

### DevStream Version

latest

**Comment by azhsmesos** [comment]
Can you assign it to me? I'd like to try it

**Comment by aFlyBird0** [comment]
> Can you assign it to me? I'd like to try it

Go ahead👏

**Comment by daniel-hutao** [comment]
closed by #1073
