### ISSUE TITLE
:bomb: `Bug`: Release Script Doesn't Exit When Error Occur

### ISSUE THREAD

**Issue by daniel-hutao** [devstream-io/devstream#1092]
### What Happened?

![4KBtdXtzsk](https://user-images.githubusercontent.com/18692628/190351187-0971878b-f24d-41d1-8e82-44b3383090a4.jpg)

Script path: `.github/workflows/automated-release.yml`

### DevStream Version

latest

**Comment by daniel-hutao** [comment]
@aFlyBird0 Would you like to enhancement the script(s)?

**Comment by aFlyBird0** [comment]
> @aFlyBird0 Would you like to enhance the script(s)?

Okay, I'ill try to fix it tomorrow
