### ISSUE TITLE
Failed to run quickstart on my machine

### ISSUE THREAD

**Issue by CrazyCollin** [devstream-io/devstream#1103]
I am a new learner of devstream. When I follow the steps of quickstart on the official website, I always make an error when I finally apply, and it always prompt that there is an error in the Map.
<img width="1037" alt="image" src="https://user-images.githubusercontent.com/79999485/190564083-b172a033-1d97-4ade-baed-8fbf6e699a23.png">

**Comment by daniel-hutao** [comment]
@CrazyCollin Hi buddy, have you resolved this problem?

**Comment by daniel-hutao** [comment]
It looks like a version drifted issue. We've changed the config format in v0.9.0, and you can refer [this document](https://docs.devstream.io/en/release-0.9/quickstart/) to try again.

**Comment by CrazyCollin** [comment]
Hi, thank you for your help. After I transferred the test platform to Linux and pulled version 0.9.0 for installation, the problem was solved
