### ISSUE TITLE
:four_leaf_clover: `Proposal`: Automatically detect binary filenames on `dtm upgrade`

### ISSUE THREAD

**Issue by aFlyBird0** [devstream-io/devstream#1110]
## What Would You Like to Add? Why Is This Needed?

When I executed `dtm upgrade`, an error occurred.

<img width="1436" alt="image" src="https://user-images.githubusercontent.com/36830265/191435915-5e34bc03-1ed7-4e66-9411-3fb6bb1e0fed.png">

Because now the name of `dtm` binary is hard coded to `"dtm"`.

https://github.com/devstream-io/devstream/blob/e13f336785363e346e10bd172c57569e9ae103f3/internal/pkg/upgrade/upgrade.go#L20

https://github.com/devstream-io/devstream/blob/e13f336785363e346e10bd172c57569e9ae103f3/internal/pkg/upgrade/upgrade.go#L123-L155

If the binary name is not `"dtm"`, such as `"dtm-darwin-arm64"`, it will occur an error.

## Design

We should be should to automatically detect binary filenames.

**Note: you can use `os.Executable()` to get the binary path.**

## Anything else

Don't forget to update related code comments.

Happy coding!

**Comment by CrazyCollin** [comment]
Maybe I can have a try
