### ISSUE TITLE
:four_leaf_clover: `Proposal`: Validate All Plugins when `make build` is Executed.

### ISSUE THREAD

**Issue by daniel-hutao** [devstream-io/devstream#1143]
## What Would You Like to Add? Why Is This Needed?

Validate all plugins when `make build` is executed.

## Design

We have a command to validate all plugins `dtm develop validate-plugin -a`. Run this validation process when `make build` is reasonable.

## Anything else

After #1140 fixed.

**Comment by aryans1319** [comment]
I would like to work on this can you assign it to me?

**Comment by daniel-hutao** [comment]
> I would like to work on this can you assign it to me?

Sure, go on!
