### ISSUE TITLE
:four_leaf_clover: `Proposal`: Add Some UT(s) for `k8s Backend`

### ISSUE THREAD

**Issue by daniel-hutao** [devstream-io/devstream#1144]
## What Would You Like to Add? Why Is This Needed?

Add some ut(s) for `k8s Backend` (internal/pkg/backend/k8s/).

## Design

No design here. You can never have too many unit tests, you're free to play here!

## Anything else

![image](https://user-images.githubusercontent.com/18692628/193053403-43b75abb-eb5f-475d-994d-d348591b2657.png)

**Comment by JoshuaPoddoku** [comment]
@daniel-hutao can we please add "hacktoberfest" tag for all GFIs?

**Comment by daniel-hutao** [comment]
> @daniel-hutao can we please add "hacktoberfest" tag for all GFIs?

I'll add the label immediately.

**Comment by Hyperbolic007** [comment]
@daniel-hutao Can i work on this issue??

**Comment by daniel-hutao** [comment]
@algobot76 You got it!

I'm so sorry for the delayed response. I was on vacation for a while.

@algobot76 @Shuimo03 @jatinagwal
