### ISSUE TITLE
:four_leaf_clover: `Proposal`: Add process bar during `dtm upgrade`

### ISSUE THREAD

**Issue by aFlyBird0** [devstream-io/devstream#1146]
## What Would You Like to Add? Why Is This Needed?

https://github.com/devstream-io/devstream/blob/e07a62162f7086232c88771f8042f6e7801511f8/internal/pkg/upgrade/upgrade.go#L88-L92

## Design

We could just refactor this function:

https://github.com/devstream-io/devstream/blob/e07a62162f7086232c88771f8042f6e7801511f8/pkg/util/scm/github/download.go#L13

Maybe you could focus on these code:

https://github.com/devstream-io/devstream/blob/e07a62162f7086232c88771f8042f6e7801511f8/pkg/util/scm/github/download.go#L49-L68

In line 63, now we use `downloader.Download` which doesn't support process bar. 
Therefore, you should refactor the function or create a new function to support process bar.

I guess this function can help you.

https://github.com/devstream-io/devstream/blob/e07a62162f7086232c88771f8042f6e7801511f8/internal/pkg/pluginmanager/pbdownloader.go#L85-L107

## Anything else

Please be brave to do some refactors. e.g. Maybe you will use `setUpProgressBar` which is in `pluginmanager` pkg and it is an unexported function. So, it is ok to change its place and export it.

**Comment by CrazyCollin** [comment]
Maybe I can have a try.

**Comment by daniel-hutao** [comment]
> Maybe I can have a try.

Hi, @CrazyCollin, the issues marked with the "good first issue" label are intended for first-time contributors. Let's save the remaining "good first issue" items for other new contributors.

**Comment by CrazyCollin** [comment]
Feel so sorry, I'll pay attention next time.
