### ISSUE TITLE
:four_leaf_clover: `Proposal`: Support for rollback in case of error in intermediate steps

### ISSUE THREAD

**Issue by aFlyBird0** [devstream-io/devstream#1173]
## What Would You Like to Add? Why Is This Needed?
https://github.com/devstream-io/devstream/blob/ed469dc9332a11be0b96c27b38d4fd507dc6508b/internal/pkg/upgrade/upgrade.go#L133-L165

**Comment by aFlyBird0** [comment]
> I want to do it

Do as much as you like!

**Comment by IronCore864** [comment]
> nd a better way to test this feature.

I think this is a way to test it, but as you said, it changes the signature of the func, which might be a bit confusing to read.

I personally suggest a better way to test it. What do you guys think?
