### ISSUE TITLE
:four_leaf_clover: `Proposal`: Integrate plugin development templates into ci checks

### ISSUE THREAD

**Issue by aFlyBird0** [devstream-io/devstream#1187]
## What Would You Like to Add? Why Is This Needed?

Currently all code of "plugin code scaffolding" is written to `string` like this:

https://github.com/devstream-io/devstream/blob/641a6f59f3016fea32161229af93efe4492d3595/internal/pkg/develop/plugin/template/create.go#L5-L39

It is challenging to find syntax errors by IDE or review. 

## Design

Run `dtm develop` to create a `dtm-test-plugin` and run `make build-plugin.dtm-test-plugin -j8` in [`.github/workflows/pr.yaml`](https://github.com/devstream-io/devstream/blob/main/.github/workflows/pr.yml) after .

## Anything else

[`dtm develop` docs](https://docs.devstream.io/en/latest/development/commands/develop/)

**Comment by aFlyBird0** [comment]
What's your opinion? Is it necessary and feasible? @daniel-hutao

**Comment by bhavyastar** [comment]
Hey, I would like to work on this? Can you please assign this to me? @aFlyBird0 @daniel-hutao

**Comment by aFlyBird0** [comment]
> Hey, I would like to work on this? Can you please assign this to me? @aFlyBird0 @daniel-hutao

Welcome to DevStream, just enjoy coding!

**Comment by bhavyastar** [comment]
Hey, @aFlyBird0 I need one help!! Can I ask a question?

**Comment by aFlyBird0** [comment]
> Hey, @aFlyBird0 I need one help!! Can I ask a question?

Feel free to ask me! :)
