### ISSUE TITLE
:four_leaf_clover: `Proposal`:  github-action plugin

### ISSUE THREAD

**Issue by steinliber** [devstream-io/devstream#1195]
## What Would You Like to Add? Why Is This Needed?
we should add a plugin for `github-action` with a more generic function. we have `golang`, `python`, `nodejs` for now, But their design is too simple. We can create a new `github-action` plugin for more generic usage.

## Design
- support sonarqube
- support multi language
- support image repo
- support notify (dingding)

**Comment by daniel-hutao** [comment]
lgtm, but could you give some more detailed design here?
