### ISSUE TITLE
:open_book: `Bug`: Rendering of https://docs.devstream.io/en/latest/development/architecture/ is not proper

### ISSUE THREAD

**Issue by SuperAayush** [devstream-io/devstream#1256]
### What should be changed?

The rendering of the complete page should be changed as it appears that CSS properties are missing from the page.
I was not able to locate the page through GUI in the docs section: https://docs.devstream.io/en/latest/ 

Link to the bug -> https://docs.devstream.io/en/latest/development/architecture/

Found the bug here (Click on the **See Architecture** button under the section -> **How DevStream Works
**) : https://www.devstream.io/

Just noticed both the links in the issue template saying [[Creating a Documentation for DevStream](https://docs.devstream.io/en/latest/development/mkdocs/)] and [[Document Translation(Chinese only)](https://docs.devstream.io/en/latest/development/translation.zh/)] also redirects to the same page

### Please read the documents below.

- [ ] I've read the document [Creating a Documentation for DevStream](https://docs.devstream.io/en/latest/development/mkdocs/) and [Document Translation(Chinese only)](https://docs.devstream.io/en/latest/development/translation.zh/). (If you want to submit a document type contribution.)

**Comment by IronCore864** [comment]
Closed by https://github.com/devstream-io/devstream/pull/1266.

Thanks @SuperAayush for raising this issue and contacting us from Slack!

BTW, we moved to CNCF's Slack channel. Find us here: https://cloud-native.slack.com/archives/C03LA2B8K0A
