### ISSUE TITLE
:open_book: `Docs`: quickstart.zh template configuration file name

### ISSUE THREAD

**Issue by bbkxm** [devstream-io/devstream#1299]
### What should be changed?

[快速开始](https://docs.devstream.io/en/latest/quickstart.zh/)
Template configuration file name should be renamed quickstart.yaml from config.yaml? Because all subsequent commands used quickstart.yaml
![image](https://user-images.githubusercontent.com/17335497/205501139-eb89c525-afbc-483e-bd5e-18d9b1baef74.png)
For Example
![image](https://user-images.githubusercontent.com/17335497/205501179-7f077328-7a05-4e43-b7a9-f2dd5d69e046.png)

### Please read the documents below.

- [x] I've read the document [Creating a Documentation for DevStream](https://docs.devstream.io/en/latest/development/mkdocs/) and [Document Translation(Chinese only)](https://docs.devstream.io/en/latest/development/translation.zh/). (If you want to submit a document type contribution.)

**Comment by aFlyBird0** [comment]
Thank you for your issue! 🚀 @bbkxm 

We have fixed it #1292 , and we will put this update into `release-0.10` branch after the Chinese version(#1297) is merged.

<img width="758" alt="image" src="https://user-images.githubusercontent.com/36830265/205502425-6f8ad03e-fd30-4a3a-9731-45e15fac5089.png">

**Comment by bbkxm** [comment]
fixed#1292
