### ISSUE TITLE
:bomb: `Bug`: Fail to apply "quick start"

### ISSUE THREAD

**Issue by tmacInChina** [devstream-io/devstream#1429]
### What Happened?

![image](https://user-images.githubusercontent.com/5390111/211998975-20184f93-8059-4511-be09-5a5f54202c04.png)

### How to Reproduce?

config:
  state: # state config, backend can be local, s3 or k8s
    backend: local
    options:
      stateFile: devstream.state

vars:
  RepoOwner: jyoujlut@sina.com
  ImageRepoUser: jiangyoujian

tools:
- name: repo-scaffolding
  instanceID: golang-github
  options:
    destinationRepo:
      owner: [[ RepoOwner ]]
      name: go-webapp-devstream-demo
      branch: main
      scmType: github
      token: [[ env GITHUB_TOKEN ]]
    sourceRepo:
      org: devstream-io
      name: dtm-repo-scaffolding-golang-gin
      scmType: github
- name: github-actions
  instanceID: default
  dependsOn: ["repo-scaffolding.golang-github"]
  options:
    scm:
      owner: [[ RepoOwner ]]
      name: go-webapp-devstream-demo
      branch: main
      scmType: github
      token: [[ env GITHUB_TOKEN ]]
    pipeline:
      configLocation: https://raw.githubusercontent.com/devstream-io/dtm-pipeline-templates/main/github-actions/workflows/main.yml
      language:
        name: go
        framework: gin
      imageRepo:
        user: [[ ImageRepoUser ]]
        password: [[ env IMAGE_REPO_PASSWORD ]]

### Anything else

dtm apply -f config.yaml -y

### DevStream Version

latest

**Comment by aFlyBird0** [comment]
I guess it's because of a problem with the RepoOwner variable setting, which should use the GitHub ID instead of the email. Try changing it to tmacInChina. @tmacInChina 

(Sorry, I replied to you yesterday, but maybe the network didn't work)
