### ISSUE TITLE
🍀 `Proposal`: Adding support for CN users

### ISSUE THREAD

**Issue by IronCore864** [devstream-io/devstream#23]
## Description

For users behind the GFW without a VPN, it's not possible to build or run using the default/official registry sources for Docker images, go modules, helm charts, and so on.

## Describe the Proposal

Add documentation about how to set:

- GOPROXY (for example, `goproxy.cn`)
- Docker registry mirrors (e.g., 官方中国区 or 阿里云等源)
- helm registry mirrors (e.g., 阿里源等其他源)

so that users behind the GFW can work and use DevStream without any problem.

Extra CLI params might be needed.

Any change _should not_ affect the current default behavior for non-GFW-blocked users.

Related to #36 which also needs to be implemented.

**Comment by daniel-hutao** [comment]
See also: #379
