### ISSUE TITLE
Tell us what project management tools do you use.

### ISSUE THREAD

**Issue by daniel-hutao** [devstream-io/devstream#367]
## Questionnaire

What project management tools do you use?

Maybe you're using `JIRA`, maybe you're using `Trello`, or maybe you're using some other tools.

Please tell us your choice and we will give `the highest priority` to the tools you are using.

---

Chinese version：

## 问卷

DevStream 想知道你正在用什么项目管理工具？

如果你正在用 Jira 或者 Trello，那么 DevStream 已经支持了，欢迎你来试用。

如果你选择的是其他工具，比如“禅道”等，也欢迎告诉我们，我们将会以最高的优先级支持你正在使用的工具！

**Comment by keepauto** [comment]
jira+禅道

**Comment by owen2016** [comment]
jira

**Comment by daniel-hutao** [comment]
/close
I collected more answers through questionnaires on WeChat.
