### ISSUE TITLE
Doc: homebrew  support

### ISSUE THREAD

**Issue by algobot76** [devstream-io/devstream#372]
## Scope

README

## Describe the Change

We have the devstream tap setup (https://github.com/devstream-io/homebrew-devstream), so it's time to demonstrate how to install `dtm` via Homebrew.

## Screenshots

n/a

## Additional Context

n/a

**Comment by IronCore864** [comment]
We have a simple README now. Would you like to enrich it a bit? @algobot76 Thanks!

**Comment by algobot76** [comment]
> We have a simple README now. Would you like to enrich it a bit? @algobot76 Thanks!

Sure. Will update README soon.
