### ISSUE TITLE
🍀 `Proposal`: I hope there will be an entry for custom Gitlab CI templates

### ISSUE THREAD

**Issue by imxw** [devstream-io/devstream#377]
## Description

The current GitLab CI pipeline plugin uses the official template which usually needs to be modified before it works on our project. In practice, we rarely use official templates directly, but often customize our own templates according to different programming languages as shown below.

<img width="354" alt="image" src="https://user-images.githubusercontent.com/16207029/161276308-f44329a0-6d0f-4e7e-b525-41631ab97ff8.png">

The `.gitlab-ci.yml` in a project can refer to these base templates, so that we only need to make a few small changes to implement a pipeline.

<img width="526" alt="image" src="https://user-images.githubusercontent.com/16207029/161278516-7797cd4f-f394-4e7c-ae60-772001f8aedc.png">

Every time I create a project I have to create a new `.gitlab-ci.yml` file, then copy and paste it and make minor changes. Even so, I still want to simplify it a bit more and turn this file all into a template and use `dtm` to push it directly to the project for me. 

So I want the plugin to provide a **template url parameter** to specify the template path, and then a **template var parameter** to replace the variables that need to be replaced in the template.

```yaml
options:
  tplUrl: https://xxx/xxx/xxx.yaml
  tplVars:
    key1: value1
    key2: value2
```
Honestly, I think this approach works not only for GitLab CI, but also for other CI tools that support `pipeline as code`.

## Describe the Alternatives You Have Considered

The template url should be able to get the template file in a subdirectory of a repository

**Comment by IronCore864** [comment]
Implemented in https://github.com/devstream-io/devstream/pull/396
