### ISSUE TITLE
Proposal: Add fig autocomplete support

### ISSUE THREAD

**Issue by imxw** [devstream-io/devstream#380]
## Description

I've been using the command line for a long time, and I'm a user of **fig autocomplete** which is very cool. It lets you add visual autocomplete to any CLI tool or script. If `dtm` supports **fig autocomplete**, I believe it will greatly  improve the user experience.

## Describe the Proposal

See https://github.com/withfig/autocomplete

## Has the Feature been Requested Before?

No

## Describe the Alternatives You Have Considered

n/a

## Additional Context

<img width="533" alt="image" src="https://user-images.githubusercontent.com/16207029/161362949-cfe1a061-8763-4034-8716-94434776b1f9.png">

<img width="555" alt="image" src="https://user-images.githubusercontent.com/16207029/161362917-603befdf-1503-4208-b68a-f534d433ee77.png">

![test](https://user-images.githubusercontent.com/16207029/161363144-1dfc2ec6-c660-4f75-9207-596d15939a24.gif)

**Comment by daniel-hutao** [comment]
This idea sounds cool!
I agree to add this feature.
I don't know what everyone thinks @devstream-io/pmc ;
If all agree, I suggest this feature can be assgin @imxw to realize.

**Comment by IronCore864** [comment]
`fig` looks nice. Please also consider alternatives like `bash-completion`, examples:
- https://kubernetes.io/docs/tasks/tools/included/optional-kubectl-configs-bash-linux/
- https://kubernetes.io/docs/tasks/tools/included/optional-kubectl-configs-bash-mac/

Make a decision using your best judgement :)

**Comment by daniel-hutao** [comment]
https://github.com/withfig/autocomplete/pull/1140

**Comment by daniel-hutao** [comment]
A document with "how to use fig along with dtm" is needed. 

@imxw @IronCore864

**Comment by imxw** [comment]
What to pay attention to when writing documents now?
