### ISSUE TITLE
Proposal: I would like to know which plugins I have installed with `dtm` and their status

### ISSUE THREAD

**Issue by imxw** [devstream-io/devstream#401]
## Description

As a user, I would like to know which plugins I have installed with `dtm` and their status by `dtm` command.

## Describe the Proposal
Examples are as follows
- `dtm list resources` gets plugins that I have installed
- `dtm show states --plugin=argo` gets the state of `argo` plugin
- `dtm show states --plugin=all`  gets the full content of the state file

## Has the Feature been Requested Before?

No

## Describe the Alternatives You Have Considered

Now all installed plugins and their status are recorded in the state file, which can be read to output the list of installed plugins and their status. 

## Additional Context

N/A

**Comment by daniel-hutao** [comment]
Great idea!

Status is actually divided into two parts:
1. The states recorded in the "State Backend"(devstream.state now)
2. The real status with the resources

So maybe we need a command to get all these two "status".

---

Command Design: 

- dtm show status # return all plugins' status
- dtm show status --plugin=PLUGIN_NAME # return the status with PLUGIN_NAME

The output message should cover the 2 parts status mentioned above.

**Comment by daniel-hutao** [comment]
If you agree with this implementation idea, I will continue to add the specific design of output information. /cc @devstream-io/devstream

**Comment by daniel-hutao** [comment]
# The printing information design

## Command: `dtm show status --plugin= demo`

### `State` (recorded in the state file) == `Resource` (state got from **Read** interface)

```sh
Name: demo
Plugin: githubactions-golang
Drift: true/false(true if State != Resource)
Options:
     // the options map printed.
Status:
    State: // required
         foo: bar // the state map printed.
    Resource: // only needed when Drift == true
         foo: bar // the resource map printed.
```

**Comment by IronCore864** [comment]
Great. Let's continue with this design.

**Comment by daniel-hutao** [comment]
There are some details that have changed, like `--name` flag. For more details, please see `Test` in #410
