### ISSUE TITLE
Proposal: New Command: `dtm develop validate-plugin --name=xxx`

### ISSUE THREAD

**Issue by daniel-hutao** [devstream-io/devstream#436]
## Description

We have `dtm develop create-plugin --name=xxx` to scaffold a new plugin.

So when someone submits a PR for a new plugin, how do we know that the plugin conforms to our scaffolding specification? 

So I want to add a command to help us with this check.

E.g. `dtm develop validate-plugin --name=xxx`

@devstream-io/devstream Who is interested?

**Comment by summingyu** [comment]
I'm interested

**Comment by daniel-hutao** [comment]
/assign @summingyu You got it.

After implement this feature, please check whether all the existing plugins are "illegal" by the way.

**Comment by IronCore864** [comment]
https://github.com/devstream-io/devstream/pull/441 solved this issue.
