### ISSUE TITLE
Proposal: `dtm list` filter flag enhancement

### ISSUE THREAD

**Issue by daniel-hutao** [devstream-io/devstream#465]
## Description

We can now use `dtm list plugins --filter {regex}` to filter the list of plugins. Thanks for @lyleshaw #462 #463

But `dtm list plugins --filter=".repo"` -> `github-repo-scaffolding-golang` is still a bit complicated. If I don't understand regex, then I don't understand what "." means here.

What if `dtm` be smarter like:

- input `--filter="repo"` -> render to `--filter=".repo."` -> output `github-repo-scaffolding-golang`
- input `--filter=".repo"` -> no render -> output `github-repo-scaffolding-golang`
- input `--filter="repo."` -> no render -> output `github-repo-scaffolding-golang`

More specifically, when the user input string by --filter contains only alphanumerics and dashes (a,a-b,a1b), we add a "." before and after (.a.,.a-b.,.a1b.).

Note: it's a good-first-issue, can only be assigned by contributors who have not submitted PR.

/cc @lyleshaw @devstream-io/pmc

**Comment by wzymumon** [comment]
I wanna try

**Comment by daniel-hutao** [comment]
> I wanna try

Cool, go ahead and happy coding!

/assign @wzymumon

**Comment by daniel-hutao** [comment]
![image](https://user-images.githubusercontent.com/18692628/167989600-b45127d0-60b5-4f7e-a8db-ec563bc8ec2b.png)

/close
