### ISSUE TITLE
💣 `Bug`: the process will crash when config file is not correct

### ISSUE THREAD

**Issue by aeinrw** [devstream-io/devstream#466]
## Describe the Bug

https://github.com/devstream-io/devstream/blob/7e1c9a6a269ae76977f2ab34bf86d871174db3cb/internal/pkg/configloader/validation.go#L78-L98

The process will panic when `c.State` is nil because of nil pointer reference in `c.State.Options`. 

By the way, how to write a config file in v.0.5.0?

**Comment by daniel-hutao** [comment]
Yeah, it should be:

```go
func validateConfigFile(c *ConfigFile) []error {
	errors := make([]error, 0)

	if c.ToolFile == "" {
		errors = append(errors, fmt.Errorf("tool file is empty"))
	}

	if c.State == nil {
		errors = append(errors, fmt.Errorf("state config is empty"))
		return errors
	}

	if c.State.Options == nil {
		errors = append(errors, fmt.Errorf("state options is empty"))
	}

	if c.State.Backend == "" {
		errors = append(errors, fmt.Errorf("backend is empty"))
	}
	return errors
}
```

Would please summit a pr to fix it? @aeinrw 

---

The config example can be seen here: `examples/quickstart.yaml` in release-0.5 branch. We'll merge it to main today.

**Comment by daniel-hutao** [comment]
#467

**Comment by daniel-hutao** [comment]
#468

**Comment by IronCore864** [comment]
@lfbdev please double check if your PR from yesterday has already fixed this.

**Comment by lfbdev** [comment]
It has been resolved, see: https://github.com/devstream-io/devstream/pull/473

**Comment by IronCore864** [comment]
@aeinrw thanks for finding out about this critical issue.

I knew that you were trying to provide a fix for it, but due to internal miscommunication, this bug was also fixed by someone else here: https://github.com/devstream-io/devstream/pull/473.

Sorry again. This should've been your contribution. But hey, don't get disappointed. See you in the next PR :)
