### ISSUE TITLE
🍀 `Proposal`: S3 Backend

### ISSUE THREAD

**Issue by algobot76** [devstream-io/devstream#485]
# Proposal: S3 Backend

## Description

Implement an S3 backend so that we can store the state file in S3.

## Assumptions

- Use `aws-sdk-go-v2` for interactions with AWS apis.
- Credentials stored in `~/.aws/credentials
- Use mocks for unit testing.

### S3Backend

```go
type S3Backend struct {
    file *S3File
}
```

```go
func NewS3Backend(bucket, region, key string) *S3Backend
```

```go
func (b *S3Backend) Read() (byte[], error)
```

```go
func (b *S3Backend) Write(data byte[]) error
```

### S3File

```go
type S3File struct {
    Bucket string
    Region string
    Key string
    ctx context.Context
    client *s3.Client
}
```

```go
func NewS3File(ctx context.Context, bucket, region, key string, client *s3.Client) (*S3File, error)
```

```go
func (f *S3File) Put(data []byte) error
```

```go
func (f *S3File) Download() ([]byte error)
```

## Has the Feature been Requested Before?

#378

**Comment by IronCore864** [comment]
Related to https://github.com/devstream-io/devstream/issues/378.
