### ISSUE TITLE
🍀`Proposal`: refactor developAction to sub-command in `dtm develop`

### ISSUE THREAD

**Issue by hxcGit** [devstream-io/devstream#493]
### Description
Now, `create-plugin` and `validate-plugin` in `dtm develop` act as Action. I think subcommand is more comfortable for them. But I'm not sure if there are other factors that should be considered here. If not, I'd be glad to submit a PR to refactor it.

**Comment by daniel-hutao** [comment]
/assign @hxcGit 

Happy coding! Your proposal is great!

**Comment by hxcGit** [comment]
I have a problem now. That is the nested sub-command in cobra won't return `unknown command` but just print usage message when the typed  sub-command is wrong. Same problem can be found [here](https://github.com/spf13/cobra/issues/706). 

I came up with some solutions.
1. Leave it alone.
2. Use cobra.NoArgs to return an error. https://github.com/spf13/cobra/issues/706#issuecomment-488340260
3. Rewrite help function like github cli. This will be a little complicated. 
@daniel-hutao @IronCore864  Can you help me?

**Comment by daniel-hutao** [comment]
@hxcGit I think it's ok to leave it alone. It's not a big thing.

![image](https://user-images.githubusercontent.com/18692628/169034762-fbc3a45a-0c12-4855-92f7-031532b84295.png)

The inconsistency between command and subcommand is acceptable for me, because both are readable and useful.

**Comment by hxcGit** [comment]
> @hxcGit I think it's ok to leave it alone. It's not a big thing.
> 
> ![image](https://user-images.githubusercontent.com/18692628/169034762-fbc3a45a-0c12-4855-92f7-031532b84295.png)
> 
> The inconsistency between command and subcommand is acceptable for me, because both are readable and useful.

The inconsistency is not in the suggestion message. The problem is shown in the following figure
![image](https://user-images.githubusercontent.com/60642406/169044270-8fcc03e8-64cd-4513-81c9-f50ba2b5035c.png)
