### ISSUE TITLE
:open_book: `Docs`: Update Chinese README

### ISSUE THREAD

**Issue by iyear** [devstream-io/devstream#496]
### What should be changed?

The current Chinese README differs greatly from the English README content, and I think it is necessary to update the Chinese README to facilitate Chinese people to read it. I will work for it.

I would probably try a paraphrase rather than a direct translation. I don't know if this is as expected.

There's a lot to translate, and I'll probably spend a few days gradually completing it

**Comment by iyear** [comment]
For some terms, do I need to add the full name in Chinese?

For example: SDLC (软件开发生命周期)

**Comment by daniel-hutao** [comment]
/assign @iyear 

Great proposal! Go ahead and happy changing!

**Comment by iyear** [comment]
#498
