### ISSUE TITLE
:open_book: `Docs`: CONTRIBUTING Doc Improvement

### ISSUE THREAD

**Issue by nikitakoselev** [devstream-io/devstream#501]
### What should be changed?

https://github.com/devstream-io/devstream/blob/main/CONTRIBUTING.md has a wrong link to the Development Workflow: https://www.devstream.io/docs/development-workflow. 

It must be something else, probably https://docs.devstream.io/en/latest/contributing/development-workflow/

![image](https://user-images.githubusercontent.com/6383738/168868670-94959336-166b-4d1d-afee-bc29cf463061.png)
![image](https://user-images.githubusercontent.com/6383738/168868749-ab219c52-be4e-4459-a522-7dc3ca94afc5.png)

**Comment by daniel-hutao** [comment]
@nikitakoselev Thanks for the bug report.
#499 has fixed it.

**Comment by IronCore864** [comment]
Fixed in https://github.com/devstream-io/devstream/pull/499

**Comment by IronCore864** [comment]
@nikitakoselev thanks very much for your attention to detail!
