### ISSUE TITLE
:bomb: `Bug`: Maybe there are print errors in `/cmd/plugin`

### ISSUE THREAD

**Issue by aFlyBird0** [devstream-io/devstream#502]
### What happened?

I'm not sure if the variables at the bottom of each file in `/cmd/plugin` are in the wrong order.

eg: 
```Go
const NAME = "argocd"
type Plugin string
var DevStreamPlugin Plugin

func main() {
	log.Infof("%T: %s is a plugin for DevStream. Use it with DevStream.\n", NAME, DevStreamPlugin)
}
```
I think it should be `DevStreamPlugin, NAME`.

Maybe I was wrong and I would be grateful if you tell me how it works.

### How to reproduce?

Just run `main()` func of any go file in `/cmd/pulgin` dir.

### DevStream version (to find out the version run: dtm version)

latest.

**Comment by IronCore864** [comment]
@aFlyBird0 thanks for your attention to detail.

In fact, each go plugin shouldn't have a main() func at all; we only have it there to shut the IDE warnings up, LOL.

Would you care to contribute a PR fixing all of those occurrences?

Thanks!

**Comment by aFlyBird0** [comment]
> @aFlyBird0 thanks for your attention to detail.
> 
> In fact, each go plugin shouldn't have a main() func at all; we only have it there to shut the IDE warnings up, LOL.
> 
> Would you care to contribute a PR fixing all of those occurrences?
> 
> Thanks!

Thank you! I'm willing to do that!

(Yep, go plugin do not need a main func. So I gotconfused. Thanks for your reply.)
