### ISSUE TITLE
:four_leaf_clover: `Proposal`: Relocate the `commitment.config.js` File to `hack/` Directory

### ISSUE THREAD

**Issue by daniel-hutao** [devstream-io/devstream#506]
## What would you like to add? Why is this needed?

![image](https://user-images.githubusercontent.com/18692628/168971755-dfeb0acf-767d-4cc5-9809-ede145989a18.png)

### Background

`commitlint.config.js` is the configuration for linting git commit messages. Currently, it's located under [build](https://github.com/devstream-io/devstream/tree/main/build)/[ci](https://github.com/devstream-io/devstream/tree/main/build/ci)/commitlint.config.js.

We also have the "hack" directory for scripts that ensure the continuous development of DevStream.

The build/ci and hack have similar purposes. It's easier if we could unify all scripts under the same folder.

### Todo

1. relocate the `commitment.config.js` file;
2. update the `lint-commit-message.yml`;
3. delete all empty dir like `build/ci/`

**Comment by SongDunYu** [comment]
I want to claim this issue
