### ISSUE TITLE
:four_leaf_clover: `Proposal`: Update the `main.go` Template File According to #503

### ISSUE THREAD

**Issue by daniel-hutao** [devstream-io/devstream#507]
## What would you like to add? Why is this needed?

See #503 for the details. It changed the `cmd/plugin/xxx/main.go`, So the `dtm develop create-plugin` diverged from the current codebase.

For more details, please reach out to @daniel-hutao.

![image](https://user-images.githubusercontent.com/18692628/168972892-ff4bfd5e-00c5-48cc-a185-cdb5bcfba84c.png)

**Comment by aFlyBird0** [comment]
Template file has been updated in #503 . 😄 

Instead, maybe it is also good add some description of how the plugin is loaded for the beginners.

e.g. The name of `DevStreamPlugin` is mandatody, so, why is it mandatory and where the code forces a dependency on this variable name?  It will be useful to beginners to understand how pulgins work.

I know what the answer is, and I want to give this pr opportunity to new commers.

**Comment by daniel-hutao** [comment]
cooool @aFlyBird0 
I thought the template file was left out, didn't expect you are so "attention to details"

**Comment by daniel-hutao** [comment]
About the docs or some comments, I think it's better to let you do it. Would you like to?

**Comment by aFlyBird0** [comment]
> cooool @aFlyBird0 
> I thought the template file was left out, didn't expect you are so "attention to details"

lol, I just use "global replace".

Then I found template files and `develop` commond. Code tracing is interesting.
