### ISSUE TITLE
:four_leaf_clover: `Proposal`: New Plugin Development: `GitLab  CE`

### ISSUE THREAD

**Issue by daniel-hutao** [devstream-io/devstream#509]
### What would you like to add? Why is this needed?

- To support local deployment of `gitlab-ce`
- Helm chart is preferred
- Please give a simple design before you start coding

/cc @devstream-io/pmc

**Comment by iyear** [comment]
Looks like a great idea, I'd like to work for it.

**Comment by daniel-hutao** [comment]
@iyear @IronCore864 

I've spent most of the day researching how to deploy gitlab-ce, and have found some rather tricky issues.

1. `gitlab-ce` doesn't have an `arm64` version or a `darwin` version of the image, so we can't run it locally. It only has the `linux/amd64` version.

![image](https://user-images.githubusercontent.com/18692628/170825806-5669f284-c280-466e-842a-843b1391f642.png)

Related issues: [Release arm64 docker images](https://gitlab.com/gitlab-org/omnibus-gitlab/-/issues/5673)

2. If we use linux to test it, resource requirements:

![image](https://user-images.githubusercontent.com/18692628/170825954-f105d1cc-673e-461a-b005-2e534cd2d2fd.png)

**Comment by daniel-hutao** [comment]
I have done some tests and have some suggestions for you @iyear:

1. `Deploy method`: For simplicity, we start with `docker` support for the first version. Refer to the [documentation here](https://docs.gitlab.com/ee/install/docker.html#install-gitlab-using-docker-engine).
2. `Docker container image`: use `docker pull gitlab/gitlab-ce:rc`
3. `OS support`: linux only(we need to remind users in the documentation that the current plugin only supports linux deployment)
4. `domain`: We give a default value, such as `gitlab.change.me`, and preserve the ability for user-defined domain names in the configuration file. e.g. `hostname=gitlab.devstream.io or domain=gitlab.devstream.io`
5. `https support`: By default, this deploy method does not support `https`, but it doesn't matter, we can leave it to the next separate proposal to avoid making the first version too complicated. For more information on how to enable https, you can see [here](https://docs.gitlab.com/omnibus/settings/nginx.html#enable-https)
6. `plugin name`: Considering that the deployment of gitlab is likely that we will have support for `vm` and `helm` in the future, I suggest that the current plugin be named `gitlab-ce-docker`

/cc @IronCore864 @aFlyBird0 Looking forward to your suggestions.

**Comment by IronCore864** [comment]
> I have done some tests and have some suggestions for you @iyear:
> 
>     1. `Deploy method`: For simplicity, we start with `docker` support for the first version. Refer to the [documentation here](https://docs.gitlab.com/ee/install/docker.html#install-gitlab-using-docker-engine).
> 
>     2. `Docker container image`: use `docker pull gitlab/gitlab-ce:rc`
> 
>     3. `OS support`: linux only(we need to remind users in the documentation that the current plugin only supports linux deployment)
> 
>     4. `domain`: We give a default value, such as `gitlab.change.me`, and preserve the ability for user-defined domain names in the configuration file. e.g. `hostname=gitlab.devstream.io or domain=gitlab.devstream.io`
> 
>     5. `https support`: By default, this deploy method does not support `https`, but it doesn't matter, we can leave it to the next separate proposal to avoid making the first version too complicated. For more information on how to enable https, you can see [here](https://docs.gitlab.com/omnibus/settings/nginx.html#enable-https)
> 
>     6. `plugin name`: Considering that the deployment of gitlab is likely that we will have support for `vm` and `helm` in the future, I suggest that the current plugin be named `gitlab-ce-docker`
> 
> 
> /cc @IronCore864 @aFlyBird0 Looking forward to your suggestions.

Great. Let's get started.

**Comment by aFlyBird0** [comment]
Iyear has been very busy recently so I will take over his task. Thank you for your previous exploratory efforts. @iyear
