### ISSUE TITLE
:four_leaf_clover: `Proposal`: Using `go-playground/validator` to Validate Plugin Config Fields

### ISSUE THREAD

**Issue by iyear** [devstream-io/devstream#511]
### What would you like to add? Why is this needed?

Currently for each field we manually validate, I think we can import a new dependency, https://github.com/go-playground/validator

we can just write tag in the fields of the struct, and the validation I proposed in #482 can be registered directly as tag to use.

**Comment by daniel-hutao** [comment]
@iyear Cooooooool proposal! I agree to use this tool!
