### ISSUE TITLE
:four_leaf_clover: `Proposal`: Plugins Enhancement

### ISSUE THREAD

**Issue by IronCore864** [devstream-io/devstream#513]
### Background

This issue is used as a "series" or "epic", which is a summary, not specific to a certain plugin.

At the moment (May 18th, 2022) we've got 18 plugins. Most plugins "work" as expected, but there is still space for improvement. For example, the following aspects could be improved:

- documentation: more background for the plugin, what it does, why use it (instead of other plugins/other ways to manage the same DevOps tool), usage example (might need some update since we release quite frequently), sample config, technical doc (for example, what's returned in the state, what's in the output), etc.
- blog posts (can be either in English or Chinese): how to use a certain plugin of DevStream to manage a certain DevOps tool
- code refactor: better variable naming, better code organization, shorter and more testable functions, shorter files, unit tests, functional tests (with Ginkgo), integrational tests (with GitHub actions e2e-test, run in a real EKS).
- configuration: maybe the current config isn't straightforward for beginners to use. Better naming of keys could help. Maybe even the options structure can be improved, too. Also, adding default values, adding more critical options (think out of the box, think from the standpoint of a real user, instead of a developer of the plugin).

### 背景

这个问题是一个“系列”，可以被关联到具体的issues，而不是特指某个插件。

目前（2022 年 5 月 18 日）我们有 18 个插件。大多数插件按预期工作，但仍有改进空间。例如，可以改进以下方面：

- 文档：插件的更多背景，它的作用，为什么使用它（而不是其他插件/其他方式来管理相同的 DevOps 工具），使用示例（可能需要一些更新，因为我们发布频繁，可能目前的状态跟使用示例已经不一致了），配置示例，技术文档（例如，状态中返回的内容，输出中的内容）等。
- 博客文章（中英文均可）：如何使用DevStream的某个插件管理某个DevOps工具
- 代码重构：更好的变量命名、更好的代码组织、更短且更可测试的函数、更短的文件、单元测试、功能测试（使用 Ginkgo）、整合测试（使用 GitHub actions的e2e-test操作，在真实 k8s 环境中运行）。
- 配置：也许当前的配置对于初学者来说并不容易使用。更好地命名键可能会有所帮助。也许甚至选项结构也可以改进。此外，添加默认值，添加更多关键选项（跳出当前的sample config的限制思考，从真实用户的角度思考，而不是插件开发人员）。

**Comment by shubham-cmyk** [comment]
_blog posts (can be either in English or Chinese): how to use a certain plugin of DevStream to manage a certain DevOps tool_

@IronCore864 Would the blogs be published on the devstream.io ?

**Comment by rxhuster** [comment]
i want to try

**Comment by daniel-hutao** [comment]
> i want to try

@rxhuster please leave your comment under a specified sub-issue
