### ISSUE TITLE
:four_leaf_clover: `Proposal`: Plugin `jenkins` Enhancement (sub-task of #513)

### ISSUE THREAD

**Issue by daniel-hutao** [devstream-io/devstream#524]
### What would you like to add? Why is this needed?

1. support test mod and prod mode meanwhile.
* test: auto-create PV named `jenkins-pv` and use host path
* prod: user can customize `storageClass`
2. use NodePort to expose service.
3. support `nodePort` config customize.
4. show Jenkins URL and tell user how to get the password of user admin
5. auto install plugins:
* GitHub Pull Request Builder
* OWASP Markup Formatter
6. docs improved.

See #513 for the details

**Comment by shubham-cmyk** [comment]
Wanna try.

**Comment by daniel-hutao** [comment]
@aFlyBird0 Please update the status of this issue

**Comment by daniel-hutao** [comment]
> Wanna try.

I'm so sorry. For the complexity of the jenkins optimization, I wrote a detailed design document and gave it to @aFlyBird0 to code.
