### ISSUE TITLE
:four_leaf_clover: `Proposal`: Plugin `helm-generic` Enhancement (sub-task of #513)

### ISSUE THREAD

**Issue by daniel-hutao** [devstream-io/devstream#531]
### What would you like to add? Why is this needed?

See #513 for the details

**Comment by daniel-hutao** [comment]
Hi @rxhuster, are you still working in this issue? Please leave your feedback if you are experiencing difficulties

**Comment by tobehardest** [comment]
Hello, I want to try to make this, can you assign it to me?
