### ISSUE TITLE
:four_leaf_clover: `Proposal`:   Need a review on cmd_apply.go

### ISSUE THREAD

**Issue by shubham-cmyk** [devstream-io/devstream#537]
###  Need a review

fmt.Errrof   & log.Errorf  is used in line 21 and 26 but NO string argument is passed. 

![Screenshot from 2022-05-19 03-51-14](https://user-images.githubusercontent.com/69793468/169165348-4a9f555a-f670-4230-9b13-09c3b834eb9a.png)

**Comment by daniel-hutao** [comment]
@shubham-cmyk Thanks for your attention-to-detail. The `log.Errorf()` should be `log.Error()` here. and `fmt.Errorf()` is ok because there haven't a `Error()` method in the `fmt` package.

**Comment by shubham-cmyk** [comment]
@daniel-hutao I have updated cmd_apply.go #539 Please go through it. 
Also it's my first commit, I am excited to do more.
