### ISSUE TITLE
:bomb: `Bug`: configloader may cause panic

### ISSUE THREAD

**Issue by aFlyBird0** [devstream-io/devstream#544]
### What happened?

![ZE7IJ38R)7Q23R1J8~`G ER](https://user-images.githubusercontent.com/36830265/169236203-c876a61f-589c-45e6-ae8a-dcc7ef384980.png)

Code is [here](https://github.com/devstream-io/devstream/blob/dcd34a4f9d5512bac5f1d4dd1da08e57d0242954/internal/pkg/configloader/config.go#L98)

## How to fix

I want to make `LoadToolConf` return `(*Config, error)`

### How to reproduce?

Please see the screenshot above

### DevStream version (to find out the version run: dtm version)

latest main branch code

**Comment by algobot76** [comment]
An alternative way to fix this issue is to call `os.Exit(1)` inside the `LoadToolConf` method if the `err !=nil`. There is no need to return `*Config` if the program can't read the cofig file.

**Comment by aFlyBird0** [comment]
> An alternative way to fix this issue is to call `os.Exit(1)` inside the `LoadToolConf` method when the `err !=nil`. There is no need to return `*Config` if the program can't read the cofig file.

Yes, I agree with you, to some extent this is the "let it panic" philosophy. As well we can use `log.Fatal(err)` instead of `os.Exit(1)`.

But on the other hand, it seems that other functions under the same package don't exit when the error is not loaded. For example `LoadConf()` in `config.go`.

**Comment by daniel-hutao** [comment]
@aFlyBird0 Yep, it's a bug. I agree with @algobot76, the easiest way to handle this bug is to:

```go
	if err != nil {
		log.Error(err)
		log.Info("Maybe the default file doesn't exist or you forgot to pass your config file to the \"-f\" option?")
		log.Info("See \"dtm help\" for more information.")
		os.Exit(1)
	}
``` 

Alternative way:

```go
cfg := LoadToolConf(toolFilePath, varFilePath)
if cfg == nil{
	return fmt.Errorf("xxx")
}
```

**Comment by daniel-hutao** [comment]
You can choose whichever way you think is the most elegant to fix this bug at your own discretion @aFlyBird0

**Comment by aFlyBird0** [comment]
Thank for you two. @algobot76 @daniel-hutao 
I still decided to stay consistent with the rest of the code and use the classic Go language pattern of `if _, err :=`.  And `/cmd` already does a uniform exit. At the same time I think having too many `Exit`s in relatively low-level functions may cause the program to get too messy.

We can have a serious discussion later if needed and then bulk change all the code related to reading the configuration.
