### ISSUE TITLE
:four_leaf_clover: `Proposal`: `dtm show status` Improvement

### ISSUE THREAD

**Issue by IronCore864** [devstream-io/devstream#557]
### Background

Currently, `dtm` supports a `show status` subcommand:

```shell
tiexin@mbp ~/work/stream $ ./dtm show --help
Show is used to print some useful information.
Examples:
  dtm show config --plugin=A-PLUGIN-NAME
  dtm show status --plugin=A-PLUGIN-NAME --name=A-PLUGIN-INSTANCE-NAME
  dtm show status -p=A-PLUGIN-NAME -n=A-PLUGIN-INSTANCE-NAME 
```

As we can see, if we run `dtm show status -p=A-PLUGIN-NAME -n=A-PLUGIN-INSTANCE-NAME`, the "status" of that plugin and that instance will be printed.

### Improvement 1

We have changed our config file. Now the parameters for this command should be "plugin" and "instanceID", so "-p=A-PLUGIN-NAME -n=A-PLUGIN-INSTANCE-NAME" isn't precise any longer.

We suggest "-p=A-PLUGIN-NAME -i=INSTANCE-ID".

### Improvement 2

Would be nice if we can `dtm show status --all` or `dtm show status -a` so that the status of all instances of all plugins are printed out.

**Comment by 24sama** [comment]
Hi @IronCore864 @daniel-hutao 
Please assign this issue to me, I can try to fix it.
