### ISSUE TITLE
:four_leaf_clover: `Proposal`: Use Validator for Config Validation

### ISSUE THREAD

**Issue by IronCore864** [devstream-io/devstream#558]
### Background

Our community member @iyear introduced https://github.com/go-playground/validator into the project in this issue https://github.com/devstream-io/devstream/issues/511 (solved by this PR https://github.com/devstream-io/devstream/pull/533). This has greatly improved our plugin options validation.

However, the `configloader` module still uses manual validation: https://github.com/devstream-io/devstream/blob/main/internal/pkg/configloader/validation.go

### Improvement

We can update the configloader's validation method to use the same validator mechanism.

It's worth noting that the logic here https://github.com/devstream-io/devstream/blob/main/internal/pkg/configloader/validation.go#L93 is a little complicated; we can implement it by something like this https://github.com/iyear/devstream/blob/9ec0591cc9a3b609b0d302d16cd6246c6119c606/internal/pkg/plugin/common/reposcaffolding/options.go#L11.

**Comment by iyear** [comment]
You may need to use rhese validations: https://github.com/go-playground/validator#other

**Comment by daniel-hutao** [comment]
@iyear Thank you for your helpful information! You must be the next community member this month!

**Comment by daniel-hutao** [comment]
`configloader` has been refactored, as can be seen in #655. So some of the links above are no longer valid, but don't worry, the `configloader` is now much more readable and you can easily find where the `validation` logic is in this package. Please don't worry, feel free to leave a comment and let us know if you encounter any problems.

**Comment by mangoGoForward** [comment]
[WeOpen Star]I would like to help
