### ISSUE TITLE
:four_leaf_clover: `Proposal`: Some Commands Do Not Need the "-f" Parameter

### ISSUE THREAD

**Issue by IronCore864** [devstream-io/devstream#559]
### What would you like to add? Why is this needed?

At the moment, we have a global parameter "-f" which is required for commands that need access to the config file.

But not all commands need it, for example:
- `dtm show`
- `dtm list`
- `dtm develop`
- etc.

But when we run:

```shell
tiexin@mbp ~/work/stream $ ./dtm show --help
Show is used to print some useful information.
Examples:
  dtm show config --plugin=A-PLUGIN-NAME
  dtm show status --plugin=A-PLUGIN-NAME --name=A-PLUGIN-INSTANCE-NAME
  dtm show status -p=A-PLUGIN-NAME -n=A-PLUGIN-INSTANCE-NAME

Usage:
  dtm show [config | status] [flags]

Flags:
  -h, --help            help for show
  -n, --name string     specify name with the plugin instance
  -p, --plugin string   specify name with the plugin

Global Flags:
  -f, --config-file string   config file (default "config.yaml")
      --debug                debug level log
  -d, --plugin-dir string    plugins directory (default ".devstream")
  -y, --yes                  apply/delete directly without confirmation
```

The "-f" flag still shows up in the help for `dtm show` subcommand, even though `dtm show` won't need it.

We can change the "-f" flag to a non-global one so that it only shows up in necessary helps of certain subcommands.

**Comment by yclchuxue** [comment]
I can do this

**Comment by shubham-cmyk** [comment]
I would also like to give it a shot

**Comment by daniel-hutao** [comment]
> I can do this

@yclchuxue It‘s a good first issue, let’s leave it to new contributor 😄

**Comment by daniel-hutao** [comment]
> shot



> I would also like to give it a shot

Hi @shubham-cmyk, let’s leave this good first issue to the new contributor😁

**Comment by shubham-cmyk** [comment]
@daniel-hutao but I have already solved it can you verify that #576 
I have removed the flag -f from the global and made specifically to the apply.go

**Comment by daniel-hutao** [comment]
#576

@shubham-cmyk Please don't open a pr before claiming the relevant issue.

**Comment by IronCore864** [comment]
Note that "show status" might need the "-f" param. Please test it thoroughly before submitting. Thanks!

**Comment by himku** [comment]
I'll try this question.

**Comment by daniel-hutao** [comment]
/assign @himku Happy coding!
Please test it thoroughly before submitting it. Thanks!
