### ISSUE TITLE
:four_leaf_clover: `Proposal`: goimports installation could be optimized by adding a condition:  if exsited, skip installation; if not existed, go on installing.   

### ISSUE THREAD

**Issue by lennyluosz** [devstream-io/devstream#571]
## What Would You Like to Add? Why is This Needed?
goimports installation could be optimized by adding a condition to decide whether to install or not 

## Design
 During goimports installation, check existance,  if exsited, skip installation; if not existed, go on installing.

**Comment by daniel-hutao** [comment]
/assign @lennyluosz 
Happy coding！

**Comment by lennyluosz** [comment]
closed by  pull request:   https://github.com/devstream-io/devstream/pull/575

**Comment by lennyluosz** [comment]
https://github.com/devstream-io/devstream/pull/575
