### ISSUE TITLE
:four_leaf_clover: `Proposal`: Enhancement: Parallel download plugins

### ISSUE THREAD

**Issue by aFlyBird0** [devstream-io/devstream#579]
## What Would You Like to Add? Why is This Needed?

Nowadays the plugins are downloaded serially, we can use parallel download to speed up.

## Design

Analyze the dependency graph and download them in batches, downloading only the plugins with dependency entry of 0 in each batch.

( Once any plugin download fails, end the entire download process)

## Anything else

Warning: There are many problems:

1. The download log may be messed up
2. The logic and syntax are complex and can easily lead to errors.
3. Maybe it is difficult to test.

**Comment by iyear** [comment]
Perhaps Docker's layer download manager and test code can be used for some reference. But Docker has to consider the parent-child relationship between layers, we'll obviously keep it simple.

Related Links:
https://github.com/moby/moby/blob/master/distribution/xfer/download.go
https://github.com/moby/moby/blob/master/distribution/xfer/download_test.go

**Comment by aFlyBird0** [comment]
> Perhaps Docker's `LayerDownloadManager` and test code can be used for some reference. But Docker has to consider the parent-child relationship between layers, we'll obviously keep it simple.
> 
> Related Links:
> https://github.com/moby/moby/blob/master/distribution/xfer/download.go
> https://github.com/moby/moby/blob/master/distribution/xfer/download_test.go

Thanks so much, referencing other proven solutions is an easy and efficient way to go! I'll take a closer look this afternoon!

**Comment by daniel-hutao** [comment]
Download speed is mainly determined by bandwidth, I feel that concurrent downloads do not significantly speed up. Maybe you can simply write a demo to test it. @aFlyBird0

**Comment by aFlyBird0** [comment]
> Download speed is mainly determined by bandwidth, I feel that concurrent downloads do not significantly speed up. Maybe you can simply write a demo to test it. @aFlyBird0

Yep, so I refactor it into a more common component to traverse tools by dependent. I am testing it now.

**Comment by aFlyBird0** [comment]
> > Download speed is mainly determined by bandwidth, I feel that concurrent downloads do not significantly speed up. Maybe you can simply write a demo to test it. @aFlyBird0
> 
> Yep, so I refactor it into a more common component to traverse tools by dependent. I am testing it now.

And maybe it is related to #566 . Because, if I solve the methods to traverse, I think it is easy to control other behaviors.
