### ISSUE TITLE
Question: how to setup trello in devstream

### ISSUE THREAD

**Issue by hxcGit** [devstream-io/devstream#586]
## Problem 
When I want to setup a trello program by dtm, I encountered the following problems.
`2022-05-23 13:13:34 ✖ [ERROR]  Errors Map: key(trello/default-Create) -> value(HTTP request failure on https://api.trello.com/1/members/me/boards:
401: invalid key)`
![image](https://user-images.githubusercontent.com/60642406/169748986-ebab1e80-c2fb-45b8-b75a-a2e2b7538a92.png)

#### 2. Set environment variables: `TRELLO_API_KEY` and `TRELLO_TOKEN`
```sh
export TRELLO_API_KEY="xxx"
export TRELLO_TOKEN="xxx"
```
And I think this is token
![image](https://user-images.githubusercontent.com/60642406/169749436-4a9b0401-4a20-4134-81b8-cbfe095ba3e4.png)

then api key
![image](https://user-images.githubusercontent.com/60642406/169749522-cc441d43-5281-46df-af15-9bd3459ba3b0.png)

I set them by `export`

#### 3. execute `dtm apply -f config.yaml`
- config.yaml
```sh
# config.yaml sample:
# var file path, you can set it to absolute path or relative path.
varFile: variables.yaml # here is a relative path. (defaults is ./variables.yaml)
# tool file path, you can set it to absolute path or relative path.
toolFile: tools.yaml # here is a relative path.
# state config
state:
  backend: local # backend can be local or s3
  options:
    stateFile: devstream.state
```
- tools.yaml
```sh
tools:
# name of the tool
- name: trello
  # id of the tool instance
  instanceID: default
  # format: name.instanceID; If specified, dtm will make sure the dependency is applied first before handling this tool
  dependsOn: []
  # options for the plugin
  options:
    # the repo's owner
    owner: hxcGit
    # the repo's org. If you set this property, then the new repo will be created under the org you're given, and the "owner" setting above will be ignored.
    org: southNorth
    # for which repo this board will be used
    repo: trelloApp
    # the Tello board name. If empty, use owner/repo as the board's name.
    kanbanBoardName: KANBAN_BOARD_NAME
```

## Environment
- macOS arm64
- dtm version: 0.6.0

**Comment by iyear** [comment]
I'm not sure if it's a token issue, but the owner and org fields only need to be filled in one.

**Comment by daniel-hutao** [comment]
> I'm not sure if it's a token issue, but the owner and org fields only need to be filled in one.
> 
> Perhaps the validation rules also need to be optimized and should only allow one field to be filled.

@iyear is right, if you setup the `options.owner`, please keep the `options.org` empty.

And please turn on the `--debug` flag then stick more logs here. @hxcGit

**Comment by hxcGit** [comment]
`--Debug` is already open. And I modified the code to print `apiKey` and `token`.
![image](https://user-images.githubusercontent.com/60642406/169773766-1b4fc78f-8feb-4c99-99fc-2ade67202722.png)

I'm not sure if I copy the right `key` and `token`.

**Comment by hxcGit** [comment]
Solved.
![image](https://user-images.githubusercontent.com/60642406/169870264-2b614f8c-bc64-49b3-b895-310e8fdd494d.png)
