### ISSUE TITLE
:four_leaf_clover: `Proposal`: Can GOPATH not need to be set?

### ISSUE THREAD

**Issue by linuxtmty** [devstream-io/devstream#587]
Goimports often cannot be found, why not get the value of GOPATH directly in the Makefile, and let the user operate the environment variable。
It's a great experience to make a small change。
<img width="678" alt="image" src="https://user-images.githubusercontent.com/8682294/169755759-0e58a004-af24-4e83-b463-2ad7cbbfe521.png">
<img width="707" alt="image" src="https://user-images.githubusercontent.com/8682294/169755820-b94f242d-7aad-499a-92e6-76eda8882966.png">

**Comment by iyear** [comment]
I think this makes sense.  I remember that GOPATH is not automatically added to PATH.

**Comment by daniel-hutao** [comment]
@linuxtmty Thanks for the great proposal, you are right! Could you please help to create a pr to fix it?

**Comment by iyear** [comment]
@linuxtmty  pr has not been created in the main repo.
