### ISSUE TITLE
:four_leaf_clover: `Proposal`: Config Template Enhancement with GitOps Support

### ISSUE THREAD

**Issue by daniel-hutao** [devstream-io/devstream#598]
## What Would You Like to Add? Why is This Needed?

We'll have `dtm show config --template=quickstart` command to print `quickstart.yaml` soon. See #597 for more details.

So why not add a `dtm show config --template=gitops` to print `gitops.yaml` to make the GitOps toolchain run easier?

## Design

`dtm show config --template=gitops` -> `gitops.yaml`

About the content with gitops.yaml, see: https://github.com/devstream-io/devstream/blob/221298b5d5dde98a67ebadb99197fcb89218f7b0/examples/gitops.yaml for the details

## Notice

Code after #597 merged

**Comment by IronCore864** [comment]
Approved. Please proceed. Great proposal!

**Comment by jxs1211** [comment]
I want to try to take this! @daniel-hutao

**Comment by daniel-hutao** [comment]
> I want to try to take this! @daniel-hutao

@jxs1211 It’s a good first issue, let’s leave it to new contributors.

**Comment by jxs1211** [comment]
> > I want to try to take this! @daniel-hutao
> 
> @jxs1211 It’s a good first issue, let’s leave it to new contributors.

ok

**Comment by karasart** [comment]
I want to try to take this! @daniel-hutao

**Comment by daniel-hutao** [comment]
> I want to try to take this! @daniel-hutao

You got it, happy coding!

**Comment by hxcGit** [comment]
@karasart  Welcome to devstream. If you have any problems in solving this problem, I am willing to assist you. You can also contact me in the devstream WeChat group, my username is LBJ.
