### ISSUE TITLE
:four_leaf_clover: `Proposal`: Move `dtm-scaffolding-golang` repo Under `devstream/staging/dtm-scaffolding-golang`

### ISSUE THREAD

**Issue by daniel-hutao** [devstream-io/devstream#610]
## What Would You Like to Add? Why is This Needed?

Last night the template repository `dtm-scaffolding-golang` that the `github-repo-scaffolding-golang` plugin depends on was deleted by mistake. Now of course I'm not trying to blame whoever deleted it, but I'm trying to figure out how to avoid this problem from happening again.

## Design

1. Use the staging directory of `devstream` repo to hold the `dtm-scaffolding-golang`;
2. Adding README.md under `devstream/dtm-scaffolding-golang` to describe the meaning of this directory;
3. Manually (and perhaps later automatically) sync the code in `devstream/dtm-scaffolding-golang` directory to `devstream-io/dtm-scaffolding-golang`;
4. Update operations for `dtm-scaffolding-golang` must pass through the master repo - `devstream`

**Comment by imxw** [comment]
Later there may be other template files, will this cause the main library to become too large
