### ISSUE TITLE
:bomb: `Bug`:  Can not run `make fmt` 

### ISSUE THREAD

**Issue by iyear** [devstream-io/devstream#613]
### What Happened?

When I run `make fmt` in `WSL` :
```
>>>>>>>>>>>> Formating codes
/bin/sh: 1: [[: not found
installing goimports ...
```

But the imports in the code does get formatted successfully

### How to Reproduce?

run `make fmt` in `WSL`

### DevStream Version

latest

**Comment by daniel-hutao** [comment]
![image](https://user-images.githubusercontent.com/18692628/170431029-10a7400d-b165-49e0-837b-c082c6fd1dba.png)

It does well in Mac. And I don't have the WSL env.

Does anyone know how to solve this compatibility problem? @devstream-io/devstream

**Comment by imxw** [comment]
The default shell used by `make` is `/bin/sh`, which in ubuntu or WSL points to the Dash Shell. The Dash Shell does not support the `[[` syntax. You can run `make fmt SHELL=$(which bash)` here.

**Comment by daniel-hutao** [comment]
@imxw Could you please help to improve it?

**Comment by imxw** [comment]
> @imxw Could you please help to improve it?

Yes! Here I want to change not only the shell, but also the way to determine whether the command exists, using `command -v` instead, it is a shell builtin, all unix-like systems can use it, and I do not think it is necessary to define GOPATH here, what do you think?

**Comment by daniel-hutao** [comment]
@imxw About the GOPATH here: https://github.com/devstream-io/devstream/issues/587

**Comment by daniel-hutao** [comment]
@iyear #623 has been merged, please check wether the issue has been fixed. And remember to close this issue if it's been fixed.

**Comment by iyear** [comment]
@daniel-hutao @imxw Thanks! It works now.

![image](https://user-images.githubusercontent.com/61452000/170707982-4726ee8e-f441-42d4-a328-7917f1f11e2f.png)
