### ISSUE TITLE
:bomb: `Bug`: github-repo-scaffolding-golang Repo Init Issues

### ISSUE THREAD

**Issue by IronCore864** [devstream-io/devstream#622]
### What Happened?

Currently, the github-repo-scaffolding-golang plugin creates a new repo, adding files to a transit branch, then merge it into the main branch.

The first file to be committed is the `.gitignore` file; so there is a logic in this plugin: if the file name is `.gitignore`, it will initialize the branch so that the commit can be successful.

However, this design heavily depends on the template repo. If `.gitignore` file doesn't exist, this plugin would fail creating a pull request.

### How to Reproduce?

Remove the `.gitignore` file from the dtm-scaffolding-golang repo and run the plugin.

### DevStream Version

latest

**Comment by daniel-hutao** [comment]
If we delete `.gitignore`, then we need to select another file to be the "first file". More detailed design is needed here.
