### ISSUE TITLE
:four_leaf_clover: `Proposal`: Add generateFigSpec subcommand for fig autocomplete

### ISSUE THREAD

**Issue by imxw** [devstream-io/devstream#627]
## What Would You Like to Add? Why is This Needed?

I want to use this subcommand to generate a `.ts` file that needed for fig autocomplete. Then integrate it into CI with [push-to-fig-autocomplete-action](https://github.com/withfig/push-to-fig-autocomplete-action), so that if there is a command or option change, the action will automatically create a Autocomplete PR.

## Design

<img width="899" alt="image" src="https://user-images.githubusercontent.com/16207029/170851427-04ae4e95-4667-4864-a5c6-aedad3177456.png">

## Anything else

In order not to affect the normal use of the user, this subcommand will not be reflected in the dtm help into and will only be used for CI

**Comment by daniel-hutao** [comment]
Good idea!

Maybe this command is a bit complicated, can we simplify it a bit more? For example, 

`dtm autocomplete --type=fig`

**Comment by imxw** [comment]
how about `dtm fig`? This subcommand will be hidden, users no need to know it. @devstream-io/pmc

**Comment by IronCore864** [comment]
@imxw has this been implemented already?

**Comment by imxw** [comment]
> @imxw has this been implemented already?

Not yet. I'll work on it later.
