### ISSUE TITLE
:four_leaf_clover: `Proposal`:  Integrate the golangci-lint command in the makefile

### ISSUE THREAD

**Issue by imxw** [devstream-io/devstream#632]
## What Would You Like to Add? Why is This Needed?

It is convenient for developers to detect problems when building locally. Improve the quality of integrating code

## Design

- `make lint`
- Determine whether the golangci-lint is installed when building. If it is not installed, install it with `go intall`

**Comment by summingyu** [comment]
Great, so is it also possible to check goimports or other installations?

**Comment by summingyu** [comment]
Or you can call it a development environment check:)
