### ISSUE TITLE
:four_leaf_clover: `Proposal`: main builder / e2e-test failure should trigger an alert

### ISSUE THREAD

**Issue by IronCore864** [devstream-io/devstream#636]
## What Would You Like to Add? Why Is This Needed?

If e2e-test is failed or if the main branch builder is failing, we should get a notification. Either Slack or Feishu.

**Comment by IronCore864** [comment]
e2e failure feishu notificaiton was implemented by @KeHaohaoke 

We are migrating to slack, though.

Please implement the same, plus main builder (UT as well, not only e2e), for slack.

**Comment by KeHaohaoke** [comment]
> e2e failure feishu notificaiton was implemented by @KeHaohaoke
> 
> We are migrating to slack, though.
> 
> Please implement the same, plus main builder (UT as well, not only e2e), for slack.

In addition to sending alerts to feishu, it also includes  the url of the actions in the alert message, so that it is easy to click to view the tracking.

**Comment by iyear** [comment]
I see that #836 has been merged, if this issue has been resolved, please close it~
