### ISSUE TITLE
:four_leaf_clover: `Proposal`: support `Tekton` plugin

### ISSUE THREAD

**Issue by imxw** [devstream-io/devstream#638]
## What Would You Like to Add? Why is This Needed?

[Tekton](https://tekton.dev/) is a powerful k8s-based cloud-native CI/CD framework, it is also a [Continuous Delivery Foundation](https://cd.foundation/) project, our plugins system should add this great member!

**Comment by IronCore864** [comment]
This has been implemented by @steinliber and @imxw. Thanks for your contribution!
