### ISSUE TITLE
:four_leaf_clover: `Proposal`:  dtm command auto-completion

### ISSUE THREAD

**Issue by prodanlabs** [devstream-io/devstream#642]
## What Would You Like to Add? Why Is This Needed?

`dtm` command  auto-completion，make `dtm` easier to use

## Anything else

![image](https://user-images.githubusercontent.com/28917392/171205753-eadcaeb0-f648-45e4-b98d-91389f6d64b5.png)

![image](https://user-images.githubusercontent.com/28917392/171206182-27a01c66-d793-400e-8d9c-12eb75e680c2.png)

**Comment by iyear** [comment]
There is currently no github bot to execute the command:(. And this issue looks similar to #627, but I don't know much about the related fields😐.

**Comment by prodanlabs** [comment]
Oh, someone is doing it, right? Then I don't have to submit a PR.

**Comment by aFlyBird0** [comment]
> There is currently no github bot to execute the command:(. And this issue looks similar to #627, but I don't know much about the related fields😐.

I think #627 is special for [`fig`](https://docs.devstream.io/en/latest/commands/autocomplete/#fig-autocomplete) , this issue is special for [`shell`](https://docs.devstream.io/en/latest/commands/autocomplete/#shell-autocomplete)

**Comment by aFlyBird0** [comment]
Thank you very much for submitting so many issues for devstream!

However, there is already an official shell autocomplete (see [here](https://docs.devstream.io/en/latest/commands/autocomplete/#shell-autocomplete) for details), so some of the functions may be duplicated.

But what does the `-p` mean? Is it a regular filter?

**Comment by aFlyBird0** [comment]
And to my partial understanding, `dtm show config -p` might be similar to `dtm list plugins -r`

![image](https://user-images.githubusercontent.com/36830265/171224843-98f2562b-8811-483e-a412-d433747490a7.png)

**Comment by prodanlabs** [comment]
```
  -p, --plugin string   specify name with the plugin
```

**Comment by prodanlabs** [comment]
```
$ ./dtm show config -p [TAB][TAB]
argocd                          githubactions-golang            github-repo-scaffolding-golang  gitlab-repo-scaffolding-golang  jenkins                         openldap
argocdapp                       githubactions-nodejs            gitlabci-generic                hashicorp-vault                 jira-github-integ               trello
devlake                         githubactions-python            gitlabci-golang                 helm-generic                    kube-prometheus                 trello-github-integ
$ ./dtm show config -p gitlab [TAB][TAB]
gitlabci-generic                gitlabci-golang                 gitlab-repo-scaffolding-golang  
```

**Comment by aFlyBird0** [comment]
> ```
> $ ./dtm show config -p [TAB][TAB]
> argocd                          githubactions-golang            github-repo-scaffolding-golang  gitlab-repo-scaffolding-golang  jenkins                         openldap
> argocdapp                       githubactions-nodejs            gitlabci-generic                hashicorp-vault                 jira-github-integ               trello
> devlake                         githubactions-python            gitlabci-golang                 helm-generic                    kube-prometheus                 trello-github-integ
> $ ./dtm show config -p gitlab[TAB][TAB]
> gitlabci-generic                gitlabci-golang                 gitlab-repo-scaffolding-golang  
> ```

Got it. I'm sorry I didn't understand at first. I'm delirious tonight.

**Comment by daniel-hutao** [comment]
@prodanlabs Great proposal!

@imxw Please help to review this proposal & pr #650

**Comment by IronCore864** [comment]
I put a description here: https://github.com/devstream-io/devstream/pull/650#issuecomment-1146951565

Is anybody interested in writing a blog on configuring auto-completion@2 with Bash 4.1+ on macOS? Chinese is fine.

@daniel-hutao
