### ISSUE TITLE
:four_leaf_clover: `Proposal`:  generate the default configuration file for the plugin based on the plugin's options

### ISSUE THREAD

**Issue by imxw** [devstream-io/devstream#643]
## What Would You Like to Add? Why Is This Needed?

Some plugins have an options.go that can be self-documented using comments, and then we can use it  to generate the xxx.yaml needed for `dtm show` using `go generate`. The markdown files in `docs/plugins` can embed the default yaml file, so that developers only need to focus on the code to avoid the situation of changing the code and forgetting to change the documentation

**Comment by daniel-hutao** [comment]
Great idea!

**Comment by IronCore864** [comment]
@aFlyBird0 I think this issue might be not too hard for first-time contributors. Maybe let's label it as a good first issue and encourage the community to work on it?

@daniel-hutao

**Comment by xiangpingjiang** [comment]
hello, can I have a try for this issue?
