### ISSUE TITLE
:four_leaf_clover: `Proposal`:  Contribution request

### ISSUE THREAD

**Issue by yxxhero** [devstream-io/devstream#651]
## What Would You Like to Add? Why Is This Needed?
I am more interested in this project. I am a community member of k8s helm Dragonfly and other projects. Please wait to participate in the devstream and improve together. I will see if there are `helm` related things in the project, which can be assigned to me. My github: https://github.com/yxxhero

**Comment by IronCore864** [comment]
Hi @yxxhero, thanks for reaching out! There sure is. Let's discuss this over Slack. Please join our slack channel and direct message me. Slack channel info is here: https://github.com/devstream-io/.

**Comment by yxxhero** [comment]
ok. Thanks very much.
