### ISSUE TITLE
:bomb: `Bug`: `dtm init` prompt error during first download

### ISSUE THREAD

**Issue by aFlyBird0** [devstream-io/devstream#654]
### What Happened?

Even if the plugin is downloaded for the first time, `dtm` still prompts "Plugin: %s already exists, no need to download.".

![image](https://user-images.githubusercontent.com/36830265/171668568-e7ac78b0-7080-4bbc-8c19-3b7a22946a2d.png)

There is a small logic bug in the code.

Related Code:
https://github.com/devstream-io/devstream/blob/8023fa202cade666d8a1f5b5a4a6c936e6eb19a3/internal/pkg/pluginmanager/manager.go#L20-L84

### How to Reproduce?

Execute `dtm init` and download the previously undownloaded plugins.

I suggest you use `release 0.6.1` instead of `release 0.6.0`.  Also, you can build dtm local.

### How to fix it?

**It's enough to just adjust `if` and `log` logic.**

### Anything else

**I think it's a `good first issue`.**

Note:      
* [Development Workflow](https://docs.devstream.io/en/latest/development/development-workflow/)
* The result of this bug fix is currently difficult to test. Because:
> If your dtm binary's MD5 sum doesn't match the MD5 sum from our release page, dtm init will stop. If your local dtm MD5 differs, it indicates that you built the binary yourself (for developing purposes, for example). Due to the nature of the Go plugin, dtm must be built together with the corresponding plugins. So, if you are building dtm, you should also build the plugins as well, in which case, you do not need to run dtm init to download the plugins.

### DevStream Version

latest

**Comment by daniel-hutao** [comment]
@aFlyBird0 It's great! You can try to sent this good-first-issue to the users and contributors WeChat groups to see if any new contributor are interested in it. If so, you can further help him to complete his first pr.

**Comment by IronCore864** [comment]
Is anybody following up on this one? @aFlyBird0

**Comment by aFlyBird0** [comment]
> Is anybody following up on this one? @aFlyBird0

I'm following up on this issue, but no new contributor has claimed the issue.

**Comment by azhsmesos** [comment]
I want to try，please assigned it to me

**Comment by aFlyBird0** [comment]
> I want to try，please assigned it to me

Welcome to DevStream! Please feel free to ask me any questions.

**Comment by azhsmesos** [comment]
> > I want to try，please assigned it to me
> 
> Welcome to DevStream! Please feel free to ask me any questions.

这个有群吗，我进去了解下devStream做的事儿

**Comment by azhsmesos** [comment]
> > 我想试试，请分配给我
> 
> 欢迎来到 DevStream！请随时问我任何问题。

这个我认为是因为逻辑中判断是否和.md5匹配，这个逻辑不管是第几次下载，只要和.md5匹配都会打印这个日志
