### ISSUE TITLE
:four_leaf_clover: `Proposal`: CoreConfig varFile & toolFile Relative Path Support

### ISSUE THREAD

**Issue by daniel-hutao** [devstream-io/devstream#660]
## What Would You Like to Add? Why Is This Needed?

![image](https://user-images.githubusercontent.com/18692628/172512605-d29b15eb-ea45-46b6-9e49-edb2dd80625d.png)

I've left the TODO there. Not the `varFile` and `toolFile` can only be `filename` or `absolute file path`, like:
1. `tools.yaml`
2. `/tmp/tools.yaml`

I wish relative paths could also be supported, like this: `../config/tools.yaml`

## Design

N/A

## Anything else

Take the first step, go for it! Feel free to contact me if you have any difficulties.

**Comment by summingyu** [comment]
I think it just needs to change
[	absFilePath := filepath.Join(filepath.Dir(filePath), filePath)](https://github.com/devstream-io/devstream/blob/221298b5d5dde98a67ebadb99197fcb89218f7b0/internal/pkg/configloader/coreconfig.go#L131)
to 
`absFilePath := filepath. Abs(filePath)`

**Comment by summingyu** [comment]
## Plan A:
Just need to change 
https://github.com/devstream-io/devstream/blob/221298b5d5dde98a67ebadb99197fcb89218f7b0/internal/pkg/configloader/coreconfig.go#L131

to `filepath.Abs()`

## Plan B:
`filepath.Abs()` will checks if the path is absolute and return abs self, so just need to change
https://github.com/devstream-io/devstream/blob/221298b5d5dde98a67ebadb99197fcb89218f7b0/internal/pkg/configloader/coreconfig.go#L115

**Comment by rxhuster** [comment]
I want try it

**Comment by daniel-hutao** [comment]
@rxhuster  happy coding！

**Comment by daniel-hutao** [comment]
@rxhuster Good job!
Please contact me on WeChat and I will prepare a certificate and some gifts for you.

---

I've tested this pr locally. Everything does well.
