### ISSUE TITLE
:four_leaf_clover: `Proposal`: Support to run e2e tests locally

### ISSUE THREAD

**Issue by hxcGit** [devstream-io/devstream#664]
## What Would You Like to Add? Why Is This Needed?

Currently dtm has support to run e2e tests in github action, but running e2e tests locally still needs to be improved.

For now, the following points maybe can be improved
1. add configuration file `config.yaml` to support local running
2. add documentation to describe how to use

**Comment by hxcGit** [comment]
assign to me

**Comment by IronCore864** [comment]
A great proposal @hxcGit. If you need any help on this matter, feel free to reach out to @daniel-hutao, @aFlyBird0, and me!
