### ISSUE TITLE
:four_leaf_clover: `Proposal`: Supports DTM version switching

### ISSUE THREAD

**Issue by huang12zheng** [devstream-io/devstream#674]
## What Would You Like to Add? Why Is This Needed?
Supports DTM version switching
1. Please download every update
2. New MAC downloads require permission

[ ] Support upgrade to latest
[ ] support downgrade order with downgrade or other similar

## Design
* in 0.6.0
dtm upgrade
> show it is now 0.6.1
* in 0.6.1
dtm downgrade
> show it is now 0.6.0

**Comment by IronCore864** [comment]
Will implement it soon. Probably will release in the next minor version. @hxcGit

**Comment by iyear** [comment]
I see that #840 has been merged. If this issue has been resolved, please close it~

**Comment by hxcGit** [comment]
@iyear  Please hold! This feature need further enhancements and feedback from users. I'll submit some PRs to improve the reliability of this feature. Maybe after the release of v0.8.0, we 'll find some bugs.
