### ISSUE TITLE
:four_leaf_clover: `Proposal`: `dtm develop` supports automatic scaffolding of the `PLUGIN_NAME.zh.md` file

### ISSUE THREAD

**Issue by aFlyBird0** [devstream-io/devstream#694]
## What Would You Like to Add? Why Is This Needed?

The docs of DevStream have supported multilingual 🎉 !

And `dtm develop` is used to help developers create a plugin easier. It scaffolds the files which a plugin needed.

Now, it can scaffold the `PLUGIN_NAME.md` file for English plugin docs. To support multilingual, it should also scaffold the `PLUGIN_NAME.zh.md` file.

## Design

We can refer to this code.

https://github.com/devstream-io/devstream/blob/main/internal/pkg/develop/plugin/template/NAME_plugin.md.go

**Comment by wenchajun** [comment]
I want to try to do it

**Comment by aFlyBird0** [comment]
> I want to try to do it

Enjoy your coding! Good Luck!

This [contributing guide](https://docs.devstream.io/en/latest/contributing_guide/)  may be useful for you. You change tap the top of the button to switch the language to Chinese.
