### ISSUE TITLE
:open_book: `Docs(Translation)`: Documentation on How to Write Documents - Chinese Version

### ISSUE THREAD

**Issue by daniel-hutao** [devstream-io/devstream#702]
### What should be changed?

#701 

Now we have the document `Creating a Documentation for DevStream`, so the corresponding Chinese version `给 DevStream 添加新文档` can also start writing (translation)

![image](https://user-images.githubusercontent.com/18692628/174574481-8dd1f0c0-24c2-4d87-9510-a05051b5ad23.png)

**Comment by jianlvliu** [comment]
I want do it.

**Comment by daniel-hutao** [comment]
@jianlvliu You got it! Happing hacking!

**Comment by daniel-hutao** [comment]
The translation does not need to correspond strictly to each sentence, it just needs to express the same meaning. "Meaningful translation" is recommended . Please feel free to ask me when you have any questions.

**Comment by daniel-hutao** [comment]
I'm soooooooo sorry, but due to a mistake by another new contributor #708, he has already finished the translation of this document.

Of course, according to the rules, this issue must belong to you. If you haven't started translating yet, I wonder if you would like to try translating other documents? I'll post a new issue right away.

If you're already translating this one, you can go ahead and submit a pr because you're eligible to claim this ticket under the rules, but I want to take care of both of you and hope you both have a good experience in contributing, so I'd like to try not to close the pr for any of you.

**Comment by daniel-hutao** [comment]
@jianlvliu e.g. #709

**Comment by daniel-hutao** [comment]
The 709 was "先斩后奏" again. I see there are several good first issue there, you can choose one you like and leave a comment. I'm really sorry.
