### ISSUE TITLE
:open_book: `Docs(Translation)`: Documentation on Contributor Ladder Version

### ISSUE THREAD

**Issue by aFlyBird0** [devstream-io/devstream#707]
### What should be changed?

<img width="383" alt="image" src="https://user-images.githubusercontent.com/36830265/174610685-45b71032-95e4-4d46-ac82-0c35fc1b8f9b.png">

---

The translation does not need to correspond strictly to each sentence, it just needs to express the same meaning. "Meaningful translation" is recommended . Please feel free to ask me when you have any questions.

**Comment by JueShanCoder** [comment]
@daniel-hutao  I got it, Tks ~

**Comment by aFlyBird0** [comment]
How is it going? Please feel free to ask for any help. :heart: @JueShanCoder

**Comment by JueShanCoder** [comment]
Sorry, The work things distract me .. I will speed up , Tks for your remind ~

**Comment by aFlyBird0** [comment]
> Sorry, The work things distract me .. I will speed up , Tks for your remind ~

This is not urgent, just make your own arrangements according to your time. 🙌
