### ISSUE TITLE
:open_book: `Docs(Translation)`: Commit Messages - Chinese Version

### ISSUE THREAD

**Issue by daniel-hutao** [devstream-io/devstream#709]
### What should be changed?

Now we have the document [Commit Messages](https://github.com/devstream-io/devstream/blob/main/docs/development/commit-messages.md), so the corresponding Chinese version can also start writing (translation) [here](https://github.com/devstream-io/devstream/blob/main/docs/development/commit-messages.zh.md).

---

The translation does not need to correspond strictly to each sentence, it just needs to express the same meaning. "Meaningful translation" is recommended . Please feel free to ask me when you have any questions.

**Comment by aucker** [comment]
I think I can do this!!!
