### ISSUE TITLE
:open_book: `Docs(Translation)`: Build & Lint - Chinese Version

### ISSUE THREAD

**Issue by daniel-hutao** [devstream-io/devstream#710]
### What should be changed?

Now we have the document [Build](https://github.com/devstream-io/devstream/blob/main/docs/development/build.md) and [Lint](https://github.com/devstream-io/devstream/blob/main/docs/development/lint.md), so the corresponding Chinese version can also start writing (translation) [here](https://github.com/devstream-io/devstream/blob/main/docs/development/build.zh.md) and [here](https://github.com/devstream-io/devstream/blob/main/docs/development/lint.zh.md).

---

The translation does not need to correspond strictly to each sentence, it just needs to express the same meaning. "Meaningful translation" is recommended . Please feel free to ask me when you have any questions.

**Comment by wendao365** [comment]
let me？

**Comment by amdaous** [comment]
I?

**Comment by daniel-hutao** [comment]
@wendao365 first, You got it! Happy hacking!

@amdaous Try another one?

**Comment by amdaous** [comment]
> @wendao365 first, You got it! Happy hacking!
> 
> @amdaous Try another one?

which one？

**Comment by wendao365** [comment]
@daniel-hutao 
I finished zhe translation, should I submit  directly？
