### ISSUE TITLE
:open_book: `Docs(Translation)`: Project Layout - Chinese Version

### ISSUE THREAD

**Issue by daniel-hutao** [devstream-io/devstream#711]
### What should be changed?

Now we have the document [Project Layout](https://github.com/devstream-io/devstream/blob/main/docs/development/project-layout.md), so the corresponding Chinese version can also start writing (translation) [here](https://github.com/devstream-io/devstream/blob/main/docs/development/project-layout.zh.md).

---

The translation does not need to correspond strictly to each sentence, it just needs to express the same meaning. "Meaningful translation" is recommended . Please feel free to ask me when you have any questions.

**Comment by IZUMI-Zu** [comment]
I want to have a try. Please assign to me.

**Comment by daniel-hutao** [comment]
@IZUMI-Zu You got it! Happy hacking!
