### ISSUE TITLE
:bomb: `Bug`: pr events always trigger doc building

### ISSUE THREAD

**Issue by imxw** [devstream-io/devstream#713]
### What Happened?

It seems that a `pull request` event will trigger the webhook of the docs deployment. I think it's dangerous because the reviewer hasn't verified the change. It is better to receive only push events from the main branch.

<img width="964" alt="image" src="https://user-images.githubusercontent.com/16207029/174634999-d007fb11-1fc9-4581-8f5f-a12cb90cb280.png">

### DevStream Version

latest

**Comment by IronCore864** [comment]
@daniel-hutao @KeHaohaoke please ensure PR no longer triggers readthedocs build.

**Comment by daniel-hutao** [comment]
/close

pr does not trigger document builds now
