### ISSUE TITLE
:open_book: `Docs(Translation)`: GitOps Toolchain - Chinese Version

### ISSUE THREAD

**Issue by daniel-hutao** [devstream-io/devstream#715]
### What should be changed?

Now we have the document [GitOps Toolchain](https://github.com/devstream-io/devstream/blob/main/docs/best-practices/gitops.md), so the corresponding Chinese version can also start writing (translation) [here](https://github.com/devstream-io/devstream/blob/main/docs/best-practices/gitops.zh.md).

---

The translation does not need to correspond strictly to each sentence, it just needs to express the same meaning. "Meaningful translation" is recommended . Please feel free to ask me when you have any questions.

**Comment by aucker** [comment]
I can do this
