### ISSUE TITLE
:open_book: `Docs`: Add "Single Config Description" in `config.md`

### ISSUE THREAD

**Issue by daniel-hutao** [devstream-io/devstream#716]
### What should be changed?

New we have "single config" support, but the [Config](https://github.com/devstream-io/devstream/blob/main/docs/core-concepts/config.md) document is out-of-date.

**Comment by IOTdailinwei** [comment]
I'm interested in this!

**Comment by IronCore864** [comment]
@IOTdailinwei sorry, the documentation has been updated. Closing this issue for now. Please search other good first issues or help wanted issues :)
