### ISSUE TITLE
:open_book: `Docs(Translation)`: Branch and Version - Chinese Version

### ISSUE THREAD

**Issue by daniel-hutao** [devstream-io/devstream#717]
### What should be changed?

Now we have the document [Branch and Version](https://github.com/devstream-io/devstream/blob/main/docs/development/branch-and-release.md), so the corresponding Chinese version can also start writing (translation) [here](https://github.com/devstream-io/devstream/blob/main/docs/development/branch-and-release.zh.md).

---

The translation does not need to correspond strictly to each sentence, it just needs to express the same meaning. "Meaningful translation" is recommended . Please feel free to ask me when you have any questions.

**Comment by hanyisong** [comment]
I want to have a try. Please assign to me.

**Comment by daniel-hutao** [comment]
@hanyisong You got it! Happy hacking!
