### ISSUE TITLE
:open_book: `Docs(Translation)`: Tool, State, and Resource - Chinese Version

### ISSUE THREAD

**Issue by daniel-hutao** [devstream-io/devstream#724]
### What should be changed?

Now we have the document [Tool, State, and Resource](https://github.com/devstream-io/devstream/blob/main/docs/core-concepts/core-concepts.md), so the corresponding Chinese version can also start writing (translation) [here](https://github.com/devstream-io/devstream/blob/main/docs/core-concepts/core-concepts.zh.md).

---

The translation does not need to correspond strictly to each sentence, it just needs to express the same meaning. "Meaningful translation" is recommended . Please feel free to ask me when you have any questions.

**Comment by daniel-hutao** [comment]
@LauraJW You got it. Hope you enjoy it!

**Comment by daniel-hutao** [comment]
@LauraJW I've updated this document, please start to translate it after #729 merged.

**Comment by IronCore864** [comment]
Hi @LauraJW, are you working on this? Please report your progress :) No pressure; if you are busy with something else, we will reassign this one to other contributors. Don't worry about it!

**Comment by LauraJW** [comment]
@IronCore864 Hi Tiexin, thanks for the follow up! I finished the task last week and asked my friend @DunyuSong to help review it. The task is not difficult but as a newbie I want to ensure that all the terms are translated correctly.

**Comment by LauraJW** [comment]
> @IronCore864 Hi Tiexin, thanks for the follow up! I finished the task last week and asked my friend @DunyuSong to help review it. The task is not difficult but as a newbie I want to ensure that all the terms are translated correctly.

I will submit asap when I ask Dunyu how to do so. Sorry for any inconvenience caused.
