### ISSUE TITLE
:four_leaf_clover: `Proposal`: Expose `image_tag` config in `gitlab-ce-docker` plugin

### ISSUE THREAD

**Issue by aFlyBird0** [devstream-io/devstream#734]
## What Would You Like to Add? Why Is This Needed?

We added a new plugin [`gitlab-ce-docker`](https://github.com/devstream-io/devstream/tree/main/internal/pkg/plugin/gitlabcedocker)  a few days ago to install gitlab-ce in docker.

However, the image tag is hardcoded now. 

https://github.com/devstream-io/devstream/blob/6d2c54a59f46c8578f8b7c086bd8175b86cb29fe/internal/pkg/plugin/gitlabcedocker/gitlabcedocker.go#L8-L19

As you can see, the image name is a `const`, and only support `rc` now.

We want to expose this var to the config file to make the user customize it.

## Design && Guides

Note: This good first issue looks like a little bit difficult. But trust me, it is easy in fact and I will give you as much guidance as I can.

### 1. Here is the config file, just put new config `image_tag` here.
https://github.com/devstream-io/devstream/blob/6d2c54a59f46c8578f8b7c086bd8175b86cb29fe/internal/pkg/show/config/plugins/gitlab-ce-docker.yaml#L9-L24

### 2. Modify the `Options` structure, which corresponds to the configuration file of the first step
https://github.com/devstream-io/devstream/blob/6d2c54a59f46c8578f8b7c086bd8175b86cb29fe/internal/pkg/plugin/gitlabcedocker/options.go#L1-L12

### 3. change the generate logic of `gitlabImageNameWithTag`

Now it is generate by two const: `gitlabImageName` and `gitlabImageTag`.

We should generate it by `gitlabImageName`  and the image tag from `options`.

## Anything else

Please feel free to ask any questions.

**Comment by wendao365** [comment]
The level is still relatively low, but I want to try my best

**Comment by aFlyBird0** [comment]
> let me?

Sorry, you are very active. Thank you sincerely. But this is "good first issue" meaning only new contributors can be assigned. And you have submitted a pr in #739 . You are our "old friends" now. 

(By the way, if this issue has not been claimed for a long time, I may transform it into "help wanted". Then you could try this.)

Do you have any other issues you want to work on? Or, just look through our source code, find something that doesn't make sense or can be improved, and feel free to submit issues and pr! @wendao365

**Comment by amdaous** [comment]
let me?

**Comment by aFlyBird0** [comment]
> let me?

Enjoy your coding!

**Comment by aFlyBird0** [comment]
> let me?

Enjoy your coding!
