### ISSUE TITLE
:four_leaf_clover: `Proposal`: Improve the folder deletion logic in plugin `gitlab-ce-docer`

### ISSUE THREAD

**Issue by aFlyBird0** [devstream-io/devstream#757]
## What Would You Like to Add? Why Is This Needed?

Now the logic of deleting volumes is completed. Even there is a bug in here. You need not know what `volumes` is (it is a term of docker), you just to know that `volumes` are some directory to store data.

1. Just delete three sub-directories rather than the whole `gitlab_home`
https://github.com/devstream-io/devstream/blob/f167bf511c4a2aba12d18b7276f0c3c525f6e26a/internal/pkg/plugin/gitlabcedocker/delete.go#L48-L53

Now we just delete the whole `gitlab_home`, but this directory can be `/` or a directory which is empty. It is dangerous.

https://github.com/devstream-io/devstream/blob/f167bf511c4a2aba12d18b7276f0c3c525f6e26a/internal/pkg/plugin/gitlabcedocker/update.go#L35-L39

Actually, we just need to delete these three sub-directories. 

2. Finish little todo here.

https://github.com/devstream-io/devstream/blob/f167bf511c4a2aba12d18b7276f0c3c525f6e26a/internal/pkg/plugin/gitlabcedocker/delete.go#L70-L71

Just check if these three sub-directories exist.

## Design

Since we will re-use the code here:

https://github.com/devstream-io/devstream/blob/f167bf511c4a2aba12d18b7276f0c3c525f6e26a/internal/pkg/plugin/gitlabcedocker/update.go#L35-L39

I think we should wrap them into a function.

Then:
1. just delete three sub-directories.
2. just check if they are deleted successfully.

## Anything else

Please feel free to ask me any questions or help. ❤️

**Comment by LuckyDogg** [comment]
I'm interested in this!

**Comment by daniel-hutao** [comment]
@LuckyDogg Enjoy your coding time!
