### ISSUE TITLE
:open_book: `Docs`: Spelling errors in core-concept.md

### ISSUE THREAD

**Issue by jxs1211** [devstream-io/devstream#778]
### What should be changed?

> # Core Concepts Overview

Let's assume you're familiar with core Git, Docker, Kubernetes, Continuous `Integratoin`, ...

`Integratoin` should be changed to `Integration`

**Comment by iyear** [comment]
Thank you for your very careful reading of our documentation!
Obviously it's a bug, you can fix it by opening a PR , looking forward to your commit!
