### ISSUE TITLE
:four_leaf_clover: `Proposal`: Remove set helm chart default timeout when validate timeout is null.

### ISSUE THREAD

**Issue by WyattJia** [devstream-io/devstream#786]
## What Would You Like to Add? Why Is This Needed?

Hi,all.

I found that when checking the helm chart timeout value, the default value is set, which is not very logical. I propose to optimize the function that sets the default timeout period. I will submit my idea to a pull request later, and I hope you can refer to it together.

![Screenshot 2022-06-30 at 10 42 41](https://user-images.githubusercontent.com/8580364/176581427-2c6999f3-2932-4b33-97d3-a5fcfe5f7e52.png)

**Comment by daniel-hutao** [comment]
@WyattJia Good thinking! Enjoy your refactoring!

**Comment by WyattJia** [comment]
> @WyattJia Good thinking! Enjoy your refactoring!

@daniel-hutao I've commited my changes and open a pull request on #788 , please and check and review my code.Thanks.
