### ISSUE TITLE
:four_leaf_clover: `Proposal(Need Discussion)`:  Optimize example config file location

### ISSUE THREAD

**Issue by aFlyBird0** [devstream-io/devstream#795]
## What Would You Like to Add? Why Is This Needed?

Since pr #794 , we could use the command line to show config. But it also brings problems: the config file is duplicated.

<img width="295" alt="image" src="https://user-images.githubusercontent.com/36830265/176816453-2715f94b-ff34-4f4c-a85d-c5bf12769b39.png">

## Design

We have two different solutions now:

### 1. Detele `/examples` and print configs only by `dtm show`.

Advantages:

1. It is easy and clear.

Disadvantages.

1. Config file nesting levels will be  too deep

### 2. update `Makefile`

We duplicated the config files because `go embed` can not embed files from parent directories.

So, why don't we add a `cp` command in `Makefile` to move config files to `/internal/pkg/show/config` ?

Advantages:

1. It is easy for users to reach config files.

Disadvantages.

1. This may be confusing for developers, and we must make it clear that the Makefile is used here to move the configuration file during `make build`.

## Anything else

Please join us to discuss! 🙌

**Comment by daniel-hutao** [comment]
Further, I want all yaml files to be in `examples` directory, including the yaml for each plugin, and make sure to keep only one copy. And the files under `/internal/pkg/show/config` or `/internal/pkg/show/config/plugins` are copied with `make`.

**Comment by daniel-hutao** [comment]
Also, I want to add a `template` directory under the /internal/pkg/show/config/ directory to save the `quickstart.yaml` and `gitops.yaml` and some template yaml files in the future.

@IronCore864 @hxcGit Please join us to discuss~

**Comment by IronCore864** [comment]
I think both solutions are not acceptable, either for first-time users, or for contributors:

1. Only showing config by `dtm show`: new users won't find examples/samples easily. Thinking from a first-time user's perspective, putting a sample config under /examples folder is mandatory. Users would be confused if there is no sample config in an obvious place in the repo.
2. Makefile: it's already complicated; moving more logic to it would only make contributor's life less happy. This solves the duplication but this brings more problems.

Based on the fact that we need "/examples/*.yaml" for new users, and we should only have a single source of yaml to remove duplication, the only logical proposal would be to remove quickstart.yaml from `dtm show`. In this case:

- single source of truth of quickstart.yaml
- if users follow our quickstart guide, they won't use `dtm show` to generate the config for quickstart; it is downloaded by a script.

**Comment by daniel-hutao** [comment]
I don't see a problem with not having an `example` directory, for example I'm not in the habit of looking at `examples`, but expecting the `cli` to tell me everything, to show me how to configure when I don't know the configuration.

I don't even want to go looking for documentation, I want the `cli` itself to be friendly enough and `-h` flag to act as documentation in as many scenarios as possible.

So I would prefer that the `Quick Start` documentation could be changed to print the configuration as a `dtm show` command instead of telling me how to download the configuration file.

Also we did see some users failed to download the config file even with the script due to network problems, and for some domestic users, every download from GitHub is an ordeal.

@IronCore864 
cc @iyear @aFlyBird0

**Comment by IronCore864** [comment]
"You" don't have a habit of looking at "examples" doesn't mean others don't.

I have a habit of looking into the examples folder to get a quicker start, and I'm sure I'm not alone.

In fact, personal preference isn't a solid argument. Thing is, having an "examples" folder will generate some benefits for some users, not for all; but not having it would do some harm to some users. So why not keep it.

I've already explained why `dtm show` or Makefile aren't good solutions. Unless we have a better solution here, I'm gonna insist on having the "examples" folder. To make things simpler, it should be used as the single source of truth.

**Comment by daniel-hutao** [comment]
After a 1-1 discussion between @IronCore864 and I, we came to an agreement on this issue.

1. Keep the `example` directory；
2. the `quickstart.yaml` and `gitops.yaml` under the `example` directory are kept;
3. `show` command behavior remains the same, the `yaml` files are copied from the `example` directory;
4. The copying behavior is implemented via the `Makefile`.

There is only one difference from the initial idea: "the `example` directory is not deleted". This is the current optimal solution.

cc @aFlyBird0 @iyear

**Comment by daniel-hutao** [comment]
After a 1-1 discussion between @IronCore864 and I, we came to an agreement on this issue.

1. Keep the `example` directory；
2. the `quickstart.yaml` and `gitops.yaml` under the `example` directory are kept;
3. `show` command behavior remains the same, the `yaml` files are copied from the `example` directory;
4. The copying behavior is implemented via the `Makefile`.

There is only one difference from the initial idea: "the `example` directory is not deleted". This is the current optimal solution.

cc @aFlyBird0 @iyear
