### ISSUE TITLE
:open_book: `Docs`: Fix broken links

### ISSUE THREAD

**Issue by aFlyBird0** [devstream-io/devstream#799]
## What Would You Like to Add? Why Is This Needed?

We already have a CI to check broken links in DevStream. Here is the result: https://github.com/devstream-io/devstream/actions/runs/2595416960

Just fix link errors.

## Anything else

1. The `./site` folder in the CI report is the actual html/js/css files generated by MkDocs after building the `/docs` folder.
2. If the link can be reached but it appears in the CI report, just tell me and need not to fix it.

**Comment by PrajwalBorkar** [comment]
I like to work on this issue , can u explain little bit about how to replace the links . Also the first [link](https://www.crunchbase.com/organization/merico) in CI is working here maybe you can remove that.

**Comment by aFlyBird0** [comment]
> I like to work on this issue , can u explain little bit about how to replace the links . Also the first [link](https://www.crunchbase.com/organization/merico) in CI is working here maybe you can remove that.

yep, this first link does work. Please feel free to comment on this issue to report tge other links. Feel free to ask me if you are not sure whether the link should be fixed.

How to fix links:

Go to `/docs` and find where this link come from, fix all of them, then submit a pr.

Do not forget to use "-s" when you commit.

**Comment by PrajwalBorkar** [comment]
Please review for any changes :)
