### ISSUE TITLE
 bug: quickstart.sh executed failed on WSL env

### ISSUE THREAD

**Issue by jxs1211** [devstream-io/devstream#801]
### What Happened?

I found dtm can't support my machine when I executed quickstart.sh
my env is WSL on windows, arch is x86_64

![image](https://user-images.githubusercontent.com/6358406/176987447-65005826-07eb-428f-b59b-4bfcb0213a91.png)

### DevStream Version

latest

**Comment by iyear** [comment]
I will work for it and try to fix it. 

In a 64-bit environment, the output of either `uname -m` or `$(arch)` is `x86_64`.
Verified on WSL Ubuntu and 64-bit CentOS server.

**Comment by iyear** [comment]
This issue has already been mentioned in #796, perhaps it is a duplicate issue.

**Comment by hxcGit** [comment]
@jxs1211 We really appreciate your feedback. As @iyear mentioned, we made a little adjustment in #798. Please try it again to see if it solves your problem. Any other suggestions are warmly welcomed.

**Comment by jxs1211** [comment]
@hxcGit 
verified.
