### ISSUE TITLE
:bomb: `Bug`: Duplicate downloads

### ISSUE THREAD

**Issue by iyear** [devstream-io/devstream#818]
### What Happened?

When using the `init` command, `dtm` checks for non-existent plugins and pulls them from the remote. However, I find that every time I use `init`, it triggers an md5 mismatch and re-downloads, even though the corresponding ones have all downloaded successfully.

I found that 

https://github.com/devstream-io/devstream/blob/1d2c60493cc5327849862dce7e8f075591b5f3ba/internal/pkg/pluginmanager/manager.go#L75-L78

There is an error in the logic of this section. Here the download has already finished, but the `StatError` used is still the one before the download, which will cause `pluginFileErr == nil && pluginMD5FileErr == nil` to never hold.

I add some debug outputs.

`log.Debug(isMD5Match, pluginFileErr, pluginMD5FileErr)`

![image](https://user-images.githubusercontent.com/61452000/177472797-6cf4f8f4-2211-4d44-a14f-3722ecf09a4f.png)

This means that every time a user uses `init`, twice as much traffic is consumed.

### How to Reproduce?

`dtm init -f quickstart.yaml --debug`

### Anything else

I will change the logic of this function and try to fix it.

Please assign me.

### DevStream Version

latest

**Comment by mangoGoForward** [comment]
I'd like to tackle this issue.

**Comment by iyear** [comment]
@mangoGoForward I'm soooo sorry, I'm already working on this.

**Comment by mangoGoForward** [comment]
> @mangoGoForward I'm soooo sorry, I'm already working on this issue.

That's nothing~

**Comment by hxcGit** [comment]
@iyear  Thank you for reporting this bug. If you come across any problems during your work, feel free to contact anyone in @devstream-io/devstream.
