### ISSUE TITLE
:bomb: `Bug`: dtm init issue

### ISSUE THREAD

**Issue by calvinxu** [devstream-io/devstream#823]
### What Happened?

I pull the latest code and wanna try the quickstart demo, but issue poped up when run dtm init 

2022-07-07 13:33:54 !! [ERROR]  Error: github-repo-scaffolding-golang-linux-amd64_0.7.0-99-gcbc3dfe.so (dev version) not exist in the local plugins dir ".devstream". Dev version plugins can't be downloaded from the remote plugin repo; please run `make build-plugin.github-repo-scaffolding-golang` to build it locally.

how can I get the build-plugin.github-repo-scaffolding-golang built?

### How to Reproduce?

$dtm init -f quickstart.yaml 
 [INFO]  Got Backend from config: local
[INFO]  Using dir <.devstream> to store plugins.
!! [ERROR]  Error: github-repo-scaffolding-golang-linux-amd64_0.7.0-99-gcbc3dfe.so (dev version) not exist in the local plugins dir ".devstream". Dev version plugins can't be downloaded from the remote plugin repo; please run `make build-plugin.github-repo-scaffolding-golang` to build it locally.

### DevStream Version

latest

**Comment by IronCore864** [comment]
Hi @calvinxu, thanks for your interest!

Our latest version is v0.7, so if you want to try the quickstart process, please follow this doc:

https://docs.devstream.io/en/release-0.7/quickstart/

Please do not use the main version of the doc.

However, if you want to try the latest main branch, you cannot run `dtm init`, instead, you have to build the plugins locally. Check out more info in the [developer guide section of our doc](https://docs.devstream.io/en/release-0.7/development/build/).

**Comment by calvinxu** [comment]
thanks, already resovled.
