### ISSUE TITLE
:four_leaf_clover: `Proposal`: Make unit test not rely on network 

### ISSUE THREAD

**Issue by steinliber** [devstream-io/devstream#827]
## What Would You Like to Add? Why Is This Needed?
The test logic in `internal/pkg/pluginmanager/downloader_test.go` will try to download file from website, this will make test slow and prone to failture. we can mock this download logic to make test smooth.

## Design
make download logic a field of `DownloadClient`，when we init class pass this func as field, like below 
<img width="1197" alt="image" src="https://user-images.githubusercontent.com/13215800/177903187-486ec74a-fe59-4aa5-8d5c-fd251546fc64.png">

**Comment by IronCore864** [comment]
Great. Let's do a mock in the unit test.
