### ISSUE TITLE
:four_leaf_clover: `Proposal`: Improve plugininstall's termination process

### ISSUE THREAD

**Issue by hxcGit** [devstream-io/devstream#887]
## What Would You Like to Add? Why Is This Needed?

Currently, our plugininstall termination process will execute all the TerminateOperations. However, in some special situation, we may prefer to execute only a few of them.

For example, in zentao plugin, the execution process consists of the following: "create namespace", "create persistent volume" and so on. In this situation, if errors are encountered when creating namespace, we don't want to delete persistent volume(It doesn't exist).

## Design
So, how about add a index to indicate at which step the error occurred. And each plugin's termination function needs to determine whether to perform this TerminationOperation based on step index.

Show as below:
```golang
// TerminationOperation only read options and execute operation
type TerminationOperation func(options RawOptions, step int) error

func (runner *Runner) Execute(options RawOptions) (map[string]interface{}, error) {

	var curInstallStep int

	// 2. register termate function if encounter in install
	var installError error
	defer func() {
		if installError == nil {
			return
		}
		log.Debugf("Start Execute Clean Operations...")
		for _, termateOperation := range runner.TermateOperations {
			err := termateOperation(options, curInstallStep)
			if err != nil {
				log.Errorf("Failed to deal with namespace: %s.", err)
			}
		}
	}()

	log.Debugf("Start Execute Install Operations...")
	// 3. Run ExecuteOperations in order, these func can't change options
	for i, installOperation := range runner.ExecuteOperations {
		curInstallStep = i
		installError = installOperation(options)
		if installError != nil {
			return nil, installError
		}
	}

}

func DealWithPersistentVolume(options plugininstaller.RawOptions, curInstallStep int) error {
	if curInstallStep < 1 {
            return nil
        }
        ···
}
```

**Comment by daniel-hutao** [comment]
There is a simple solution: to change the logic of the `delete` operation to `deleteIfExists`
