### ISSUE TITLE
:four_leaf_clover: `Proposal`:  support apply config directory

### ISSUE THREAD

**Issue by steinliber** [devstream-io/devstream#913]
## What Would You Like to Add? Why Is This Needed?
We support getting config from a file for now. but for more complex config maybe using a directory to save configs is a better choice.

## Design
- if the user run the command `dtm apply -f {{dir_name}}`, dtm should read all config files in this directory and generate config for the following process

**Comment by daniel-hutao** [comment]
We have previously considered supporting directories as a way to pass in configuration files, but that may not be necessary at now because the configuration has not become so complex, and currently splitting the configuration into multiple files may make dtm a little more difficult to use.

**Comment by daniel-hutao** [comment]
If it's because the current config file is already too long, I agree with splitting.
