### ISSUE TITLE
:bomb: `Bug`: repo-scaffolding-darwin-arm64_0.7.0.so download failed, 403 Forbidden.

### ISSUE THREAD

**Issue by sinkcup** [devstream-io/devstream#924]
### What Happened?

<img width="1370" alt="image" src="https://user-images.githubusercontent.com/4971414/181677291-d90b0fd9-a482-4420-a513-5a03e67bf98c.png">

### How to Reproduce?

1. install dtm on macOS ARM64(CPU: Apple M1 Pro)
2. config env
3. run `dtm init -f quickstart.yaml`

### DevStream Version

v0.7.0

**Comment by iyear** [comment]
@sinkcup Sorry, we have some problems with the documentation. release-0.7 has a link in the documentation that contains the main branch. We'll fix it later, sorry about that!

Here is the 0.7.0 version of `quickstart.yaml`:
https://raw.githubusercontent.com/devstream-io/devstream/release-0.7/examples/quickstart.yaml

**Comment by iyear** [comment]
Fixed by #925
