### ISSUE TITLE
:bomb: `Bug`: Misleading log message 

### ISSUE THREAD

**Issue by warren830** [devstream-io/devstream#928]
### What Happened?

After I build `stream` locally, when I tried run `./dtm init -f config.yml`, report the following error:
![SYry81JMMm](https://user-images.githubusercontent.com/39366025/182012161-2b951815-9636-41c7-a350-c867eff9a5f8.png)

I am not sure if this log info should appear in another place.

### How to Reproduce?

1. Build stream locally
2. run `./dtm init -f config.yml`
3. the error was shown

### DevStream Version

latest

**Comment by iyear** [comment]
My bad, it should be moved to download function. I will fix it.

**Comment by IronCore864** [comment]
Closed by https://github.com/devstream-io/devstream/pull/929.
