### ISSUE TITLE
:four_leaf_clover: `Proposal`: ignore `*.state`

### ISSUE THREAD

**Issue by aFlyBird0** [devstream-io/devstream#948]
## What Would You Like to Add? Why Is This Needed?

Currently `.gitignore` only ignores the default `devstream.state` file.

But we may have multiple state files when we test more than one plugin in the meantime, such as `jenkins.state`, `harbor.state`.

I recommend ignoring all state files.

## Design
<img width="251" alt="image" src="https://user-images.githubusercontent.com/36830265/182992696-82def7ee-71f8-4e80-820c-db1411ef55a9.png">

**Comment by daniel-hutao** [comment]
lgtm

I'll fix it btw.
