### ISSUE TITLE
:bomb: `Bug`: GitHub Api rate limit exceeded

### ISSUE THREAD

**Issue by csonezp** [devstream-io/devstream#955]
### What Happened?

quickstart.sh will get the latest version from ```https://api.github.com/repos/devstream-io/devstream/releases/latest```.
but this url has a ratelimter.

Please assign it to me,i will fix it asap.

### DevStream Version

latest

**Comment by aFlyBird0** [comment]
Thanks for your feedback on adapting our quick start script to more network environments! @csonezp

**Comment by csonezp** [comment]
resolved by #957
