### ISSUE TITLE
:four_leaf_clover: `Proposal`: repo scaffolding should protect the default main branch

### ISSUE THREAD

**Issue by IronCore864** [devstream-io/devstream#963]
## What Would You Like to Add? Why Is This Needed?

After repo scaffolding, in the new repo, there is a warning by GitHub: 

Your main branch isn't protected

Protect this branch from force pushing, deletion, or require status checks before merging.

## Design

We should protect the default main branch of a newly created repo in GitHub.

**Comment by csonezp** [comment]
Let me try, please assign it to me.

**Comment by daniel-hutao** [comment]
@csonezp You get it! Enjoy you coding time.
