### ISSUE TITLE
:four_leaf_clover: `Proposal`: Proposing a new member @jxs1211 

### ISSUE THREAD

**Issue by iyear** [devstream-io/devstream#974]
## What Would You Like to Add? Why Is This Needed?
@jxs1211  contributed nearly 20 PR and thousand lines of code to `DevStream`, allowing 100% test coverage for many packages, while filling in the gaps of many hard-to-write unit tests. 

Also, he shared many valuable suggestions and experiences in the community huddle. For example, contributors who are new to `DevStream` can try to start with unit tests to quickly understand the project after finishing the `good first issue`.

An Organization Member _must meet the responsibilities and has the requirements of a Contributor_, plus:

- Responsibilities:
    - Continues to contribute regularly, as demonstrated by having at least 50 GitHub contributions per year, as demonstrated by [GitHub Insights](https://github.com/devstream-io/devstream/pulse).

- Requirements:
    - Must have successful contributions to the project, including at least one of the following:
        - 5 accepted PRs,
        - Reviewed 5 PRs,
        - Resolved and closed 5 Issues,
        - Become responsible for a key project management area,
        - Or some equivalent combination or contribution
    - Must have been contributing for at least 1 months
    - Must be actively contributing to at least one project area
    - Must have two sponsors who are also Organization Members, at least one of whom does not work for the same employer

- Privileges:
    - May be assigned Issues and Reviews
    - May give commands to CI/CD automation
    - Entitled to vote in elections [TODO]
    - Can be added to @devstream-io/devstream  teams
    - Can recommend other contributors to become Org Members

Need approvals from @devstream-io/devstream.

**Comment by daniel-hutao** [comment]
lgtm

**Comment by aFlyBird0** [comment]
Welcome to the DevStream family! @jxs1211 👏

**Comment by aFlyBird0** [comment]
(Need another approval from a different company 👀)

**Comment by IronCore864** [comment]
> (Need another approval from a different company 👀)

@imxw please have a look at their recent contributions and make a decision:) We need your input.

**Comment by imxw** [comment]
> > (Need another approval from a different company 👀)
> 
> @imxw please have a look at their recent contributions and make a decision:) We need your input.

lgtm. I was impressed by his contribute.
